Repository codeit-bootcamp-frontend/4-Weekly-Mission, pull requests merged in 2024-03, with the labels that each got.

#730 [심민보] week9
  public/index.html
  src/componenets/LinkAdd.jsx
  src/componenets/modal/AddAtFolder.jsx
  src/componenets/modal/Modal.jsx
  src/componenets/modal/SharedFolder.jsx
  src/componenets/modal/modal.css
Labels: 매운맛🔥

#732 [박기범] week8
  .vscode/settings.json
  package-lock.json
  package.json
  src/Main.js
  src/api.js
  src/assets/add.svg
  src/assets/addGray.svg
  src/assets/delete.svg
  src/assets/kebab.svg
  src/assets/link.svg
  src/assets/pen.svg
  src/assets/share.svg
  src/assets/star.svg
  src/components/App.js
  src/components/CardList.css
  src/components/CardList.js
  src/components/CardSection.css
  src/components/CardSection.js
  src/components/FolderBar.js
  src/components/FolderSection.css
  src/components/FolderSection.js
  src/components/Footer.js
  src/components/LinkAdd.css
  src/components/LinkAdd.js
  src/components/NavigationBar.js
  src/components/SearchBar.css
  src/components/SearchBar.js
  src/index.js
  src/pages/App.css
  src/pages/App.js
  src/pages/FolderPage.css
  src/pages/FolderPage.js
Labels: 순한맛🐑 

#767 [김동현] Week8
  .env
  package-lock.json
  package.json
  public/index.html
  public/robots.txt
  src/App.css
  src/App.jsx
  src/api.js
  src/api/api.js
  src/assets/png/avatar.png
  src/assets/png/base.png
  src/assets/png/icon_google.png
  src/assets/png/icon_kakao.png
  src/assets/png/profile.png
  src/assets/svg/add.svg
  src/assets/svg/delete.svg
  src/assets/svg/icon_facebook.svg
  src/assets/svg/icon_instagram.svg
  src/assets/svg/icon_twitter.svg
  src/assets/svg/icon_youtube.svg
  src/assets/svg/kebab.svg
  src/assets/svg/link.svg
  src/assets/svg/logo.svg
  src/assets/svg/pen.svg
  src/assets/svg/search.svg
  src/assets/svg/share.svg
  src/assets/svg/star.svg
  src/color.css
  src/components/AddLinkBar.css
  src/components/AddLinkBar.js
  src/components/App.css
  src/components/App.js
  src/components/Banner.css
  src/components/Banner.js
  src/components/Body.css
  src/components/Body.js
  src/components/ButtonList.js
  src/components/CardList.css
  src/components/CardList.js
  src/components/CardListItem.css
  src/components/CardListItem.js
  src/components/CardsArea.css
  src/components/CardsArea.js
  src/components/Footer.css
  src/components/Footer.js
  src/components/Gnb.css
  src/components/Gnb.js
  src/components/Header.css
  src/components/Header.js
  src/components/SearchBar.css
  src/components/SearchBar.js
  src/components/util/date.js
  src/components/util/timeAgo.js
  src/global.css
  src/index.js
  src/pages/folder/FolderPage.css
  src/pages/folder/FolderPage.js
  src/pages/share/SharePage.css
  src/pages/share/SharePage.js
  src/reset.css
Labels: 매운맛🔥

#745 [임동현] week9
  public/images/check.svg
  public/images/close.svg
  public/images/facebookShare.png
  public/images/kakaoShare.png
  public/images/linkShare.png
  public/index.html
  src/assets/common/common.css
  src/components/common/Header.css
  src/components/form/SearchInput.js
  src/components/modal/modal.css
  src/components/modal/modal.js
  src/index.js
  src/pages/folder/AddLink.css
  src/pages/folder/AddLink.js
  src/pages/folder/Folder.js
  src/pages/folder/FolderButton.js
  src/pages/folder/FolderContents.js
  src/pages/folder/folderTitle.css
  src/pages/folder/folderTitle.js
  src/pages/folder/kebabModal.js
  src/pages/shared/SharedContents.css
  src/pages/shared/UserTitle.css
  src/store/store.js
Labels: 매운맛🔥

#722 [여승구] Week9
  .eslintrc.js
  package-lock.json
  package.json
  public/images/check.svg
  public/images/close.svg
  public/images/facebookShare.png
  public/images/kakaoShare.png
  public/images/linkShare.png
  public/index.html
  src/App.js
  src/Data/getData.js
  src/components/AddRemoveButton/AddRemoveButton.js
  src/components/CardList/CardListFolder.js
  src/components/FolderMenu/FolderMenu.js
  src/components/Footer/Footer.js
  src/components/Modal/Modal.css
  src/components/Modal/Modal.js
  src/layout/ShareLayout/index.js
  src/utils/constant.js
Labels: 매운맛🔥

#714 [최수민] Week8
  package-lock.json
  package.json
  src/Main.jsx
  src/api.js
  src/assets/Linkbrary.svg
  src/assets/SearchIcon.svg
  src/assets/add.svg
  src/assets/addblue.svg
  src/assets/kebab.svg
  src/assets/linkicon.svg
  src/assets/pen.svg
  src/assets/share.svg
  src/assets/shared/akar-icons_facebook-fill.svg
  src/assets/shared/akar-icons_twitter-fill.svg
  src/assets/shared/akar-icons_youtube-fill.svg
  src/assets/shared/ant-design_instagram-filled.svg
  src/assets/star.svg
  src/assets/trash.svg
  src/assets/이미지 없을 때 배경.svg
  src/components/AddLinkBar.jsx
  src/components/App.js
  src/components/Cards.js
  src/components/Cards.jsx
  src/components/CatagoryBtns.jsx
  src/components/FloatingBtn.jsx
  src/components/FolderProfile.js
  src/components/FolderProfile.jsx
  src/components/FoldersCatagory.jsx
  src/components/FoldersLinks.jsx
  src/components/FoldersMain.jsx
  src/components/Footer.js
  src/components/Footer.jsx
  src/components/Layout.jsx
  src/components/Loading.jsx
  src/components/LoginBtn.jsx
  src/components/MainContents.js
  src/components/NavBar.js
  src/components/NavBar.jsx
  src/components/NoLinkSection.jsx
  src/components/SearchBar.js
  src/components/SearchBar.jsx
  src/components/hooks/useFetch.js
  src/index.js
  src/index.jsx
  src/pages/ErrorPage.jsx
  src/pages/FaqPage.jsx
  src/pages/FolderPage.jsx
  src/pages/HomePage.jsx
  src/pages/PrivacyPolicyPage.jsx
  src/pages/SharedPage.jsx
  src/pages/SigninPage.jsx
  src/pages/SignupPage.jsx
  src/style/theme.js
Labels: 매운맛🔥

#724 [길수진] week9
  public/index.html
  src/App.jsx
  src/Routers/Routers.jsx
  src/assets/css/app.module.css
  src/assets/css/reset.css
  src/assets/images/ic_close.png
  src/assets/images/ic_facebook.svg
  src/assets/images/ic_kakao.svg
  src/components/Card/Card.jsx
  src/components/Card/card.module.css
  src/components/CardList/CardList.jsx
  src/components/Modal/BaseModal/BaseModal.jsx
  src/components/Modal/BaseModal/base.module.css
  src/components/Modal/DeleteModal/DeleteModal.jsx
  src/components/Modal/DeleteModal/delete.module.css
  src/components/Modal/FolderModal/FolderModal.jsx
  src/components/Modal/FolderModal/folder.module.css
  src/components/Modal/SharedModal/SharedModal.jsx
  src/components/Modal/SharedModal/shared.module.css
  src/layout/Footer/Footer.jsx
  src/layout/Navbar/navbar.module.css
  src/pages/FolderPage/FolderPage.jsx
  src/pages/FolderPage/components/ActionButton/ActionButton.jsx
  src/pages/FolderPage/components/ActionButton/actionButton.module.css
  src/pages/FolderPage/components/Category/Category.jsx
  src/pages/FolderPage/components/Category/category.module.css
  src/pages/FolderPage/components/Header.jsx
  src/pages/FolderPage/folder.module.css
  src/services/api.js
  src/utils/constants/strings.js
  src/utils/hooks/useFetch.js
  src/utils/hooks/useModal.js
Labels: 매운맛🔥

#758 [강진호] week9
  package-lock.json
  package.json
  public/index.html
  src/assets/images/check.svg
  src/assets/images/close.svg
  src/assets/images/share-facebook.svg
  src/assets/images/share-kakao.svg
  src/assets/images/share-link-copy.svg
  src/assets/images/star.svg
  src/assets/styles/colors.css
  src/assets/styles/utility.css
  src/components/Common/AddFolderList.js
  src/components/Common/AddFolderList.module.css
  src/components/Common/AddLInkButton.js
  src/components/Common/Button.js
  src/components/Common/LoginButton.js
  src/components/Common/ModalButton.js
  src/components/Common/ModalButton.module.css
  src/components/Common/Option.js
  src/components/Common/SelectMenu.js
  src/components/Common/SelectMenu.module.css
  src/components/Common/SortingButton.js
  src/components/Common/StarButton.js
  src/components/Common/TextInput.js
  src/components/Common/TextInput.module.css
  src/components/Header/AddLinkBar.js
  src/components/Header/AddLinkBar.module.css
  src/components/Header/Gnb.js
  src/components/Main/Card.js
  src/components/Main/Card.module.css
  src/components/Main/CardList.js
  src/components/Main/SearchBar.js
  src/components/Main/SortingSection.js
  src/components/Main/SortingSection.module.css
  src/components/Modal/AddFolderModal.js
  src/components/Modal/AddFolderModal.module.css
  src/components/Modal/AddToFolderModal.js
  src/components/Modal/AddToFolderModal.module.css
  src/components/Modal/DeleteFolderModal.js
  src/components/Modal/DeleteFolderModal.module.css
  src/components/Modal/DeleteLinkModal.js
  src/components/Modal/DeleteLinkModal.module.css
  src/components/Modal/EditFolderNameModal.js
  src/components/Modal/EditFolderNameModal.module.css
  src/components/Modal/ModalContainer.js
  src/components/Modal/ModalContainer.module.css
  src/components/Modal/ShareModal.js
  src/components/Modal/ShareModal.module.css
  src/context/Modal.js
  src/context/ModalContext.js
  src/context/ModalProvider.js
  src/hooks/useModal.js
  src/index.js
  src/pages/HomePage/HomePage.js
  src/pages/HomePage/HomePage.module.css
Labels: 매운맛🔥

#786 [차수지] Week9
  public/assets/folder/close.svg
  public/assets/folder/facebook.svg
  public/assets/folder/kakao.svg
  public/assets/folder/link.svg
  src/Router.jsx
  src/components/modal/Modal.jsx
  src/components/modal/Modal.style.js
  src/components/modal/share-button/ShareButton.jsx
  src/components/wide-button/WideButton.jsx
  src/components/wide-button/WideButton.style.js
  src/pages/test.jsx
Labels: 미완성

#698 [이서인] Week9
  package-lock.json
  package.json
  public/images/add.svg
  public/images/addWhite.svg
  public/images/kebab.png
  public/images/linkIcon.svg
  public/images/noImage.png
  public/images/star.png
  public/index.html
  src/components/Card/Card.css
  src/components/Card/Card.jsx
  src/components/FilterBar/FilterBar.jsx
  src/components/Header/Header.jsx
  src/components/Header/HeaderFolder.jsx
  src/components/Main/MainFolder.jsx
  src/components/Modals/ ShareModal.jsx
  src/components/Modals/AddFolderModal.jsx
  src/components/Modals/EditModal.jsx
  src/components/Modals/Modal.css
  src/components/Section/Section.css
  src/components/Section/Section.jsx
  src/components/Section/SectionFolder.jsx
  src/components/pages/folder.jsx
  src/dataAccessLink/useGetLink.jsx
  src/hooks/useAsync.jsx
  src/index.css
Labels: 매운맛🔥

#790 [정사비비] Week9
  src/App.js
  src/GlobalStyle.js
  src/api.js
  src/common/styles/color.css
  src/common/styles/global.css
  src/components/Card.js
  src/components/Footer.js
  src/components/Layout.js
  src/components/folder/FolderItem.js
  src/components/folder/FolderList.js
  src/components/folder/FolderTabItem.js
  src/components/folder/Tab.js
  src/components/header/FolderTitle.js
  src/components/header/Header.js
  src/components/modal/ModalContainer.js
  src/components/modal/ModalPopupAdd.js
  src/components/modal/ModalPopupAddToFolder.js
  src/components/modal/ModalPopupDelete.js
  src/components/modal/ModalPopupDeleteLink.js
  src/components/modal/ModalPopupEdit.js
  src/components/modal/ModalPopupShare.js
  src/components/modal/styles/modalContainer.css
  src/components/modal/styles/modalPopupAddToFolder.module.css
  src/components/modal/styles/modalPopupDelete.css
  src/components/modal/styles/modalPopupShare.css
  src/components/shared/Card.js
  src/components/shared/SharedCardList.js
  src/components/styles/card.css
  src/components/styles/footer.css
  src/components/styles/header.css
  src/images/check.svg
  src/images/close.svg
  src/images/delete.svg
  src/images/kakao.svg
  src/images/modal_facebook.svg
  src/images/modal_link.svg
  src/images/pen.svg
  src/images/share.svg
  src/index.css
  src/pages/FolderPage.js
  src/pages/HomePage.js
  src/pages/SharedPage.js
  src/pages/styles/FolderPage.module.css
Labels: 미완성, 순한맛🐑 

#783 [김혜중]week9
  src/api.js
  src/components/Account/index.css
  src/components/Account/index.js
  src/components/CardGrid/Cardgrid.js
  src/components/CardGrid/Cardgrid.scss
  src/components/Common/Nav.js
  src/components/LinkForm/index.js
  src/components/LinkForm/index.scss
  src/components/Modal/AddFolder.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.scss
  src/components/Modal/Portal.jsx
  src/image/modal-close.svg
  src/image/modal-facebook.svg
  src/image/modal-kakao.svg
  src/image/modal-link.svg
  src/style/color.css
Labels: 미완성

#772 [박현우] Week9
  package-lock.json
  weekly-mission/public/index.html
  weekly-mission/src/App.js
  weekly-mission/src/api.js
  weekly-mission/src/components/CategoryBar.js
  weekly-mission/src/components/Footer.js
  weekly-mission/src/components/Header.js
  weekly-mission/src/components/LinkAddInput.js
  weekly-mission/src/components/LinkCard.js
  weekly-mission/src/components/Loading.js
  weekly-mission/src/components/Login.js
  weekly-mission/src/components/ModalDelete.js
  weekly-mission/src/components/ModalFolderEdit.js
  weekly-mission/src/components/ModalLayout.js
  weekly-mission/src/components/ModalLinkAdd.js
  weekly-mission/src/components/ModalShare.js
  weekly-mission/src/components/OwnerInformation.js
  weekly-mission/src/components/Profile.js
  weekly-mission/src/components/SearchInput.js
  weekly-mission/src/constant.js
  weekly-mission/src/img/Kakao.png
  weekly-mission/src/img/check.png
  weekly-mission/src/img/close.png
  weekly-mission/src/index.css
  weekly-mission/src/index.js
  weekly-mission/src/pages/Folder.css
  weekly-mission/src/pages/Folder.js
  weekly-mission/src/pages/Shared.css
  weekly-mission/src/pages/Shared.js
  weekly-mission/src/utils.js
Labels: 매운맛🔥

#792 [황경수] week9
  public/index.html
  src/assets/image/facebook.png
  src/assets/image/kakao.png
  src/assets/svg/check.svg
  src/assets/svg/close.svg
  src/assets/svg/share_facebook.svg
  src/assets/svg/share_kakao.svg
  src/assets/svg/share_link.svg
  src/components/Modal/FolderAddList.jsx
  src/components/Modal/ModalBase.jsx
  src/components/Modal/ModalWithInput.jsx
  src/components/Modal/ShareSnsList.jsx
  src/components/common/Backdrop.jsx
  src/components/common/Header.jsx
  src/components/common/SearchBar.jsx
  src/components/folder/AddLink.jsx
  src/components/folder/Dropdown.jsx
  src/components/folder/FoderOptionMenu.jsx
  src/components/folder/FolderInfo.jsx
  src/components/shared/Card.jsx
  src/pages/Folder.jsx
Labels: 매운맛🔥

#810 [박지윤] Week13
  .eslintrc.json
  .prettierrc.json 
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.tsx
  src/api/fetchFolders.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/Profile.tsx
  src/components/folder/FolderContent.tsx
  src/components/folder/FolderLinks.tsx
  src/components/folder/KebabMenu.tsx
  src/components/folder/LinkCards.tsx
  src/components/folder/Modal.tsx
  src/components/folder/buttons/ActionContainer.tsx
  src/components/folder/buttons/FolderAddButton.tsx
  src/components/folder/buttons/FolderCategoryButtons.tsx
  src/components/folder/common/FolderNav.tsx
  src/components/folder/common/FolderProfile.tsx
  src/components/folder/common/LinkForm.tsx
  src/components/folder/common/SearchBar.tsx
  src/components/shared/Cardlist.tsx
  src/components/shared/Nav.tsx
  src/custom.d.ts
  src/hooks/FolderContainer.tsx
  src/hooks/useCardContainer.tsx
  src/hooks/useFolderContainer.tsx
  src/hooks/useModal.tsx
  src/index.tsx
  src/pages/folder.tsx
  src/pages/shared.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/utils/dateUtils.tsx
  tsconfig.json
Labels: 미완성, 순한맛🐑 

#827 [남현준] week13
  week7/package-lock.json
  week7/package.json
  week7/src/App.tsx
  week7/src/EmptyPage.tsx
  week7/src/FolderPage.tsx
  week7/src/Main.jsx
  week7/src/SharedPage.js
  week7/src/SharedPage.tsx
  week7/src/api.js
  week7/src/assets/close.png
  week7/src/components/Card.tsx
  week7/src/components/Folder.tsx
  week7/src/components/FolderPage/AddLink.css
  week7/src/components/FolderPage/AddLink.js
  week7/src/components/FolderPage/AddLink.tsx
  week7/src/components/FolderPage/FolderCard.tsx
  week7/src/components/FolderPage/FolderHeader.css
  week7/src/components/FolderPage/FolderHeader.tsx
  week7/src/components/FolderPage/SortedMenus.tsx
  week7/src/components/Footer.tsx
  week7/src/components/Header.css
  week7/src/components/Header.tsx
  week7/src/components/Input.js
  week7/src/components/Input.tsx
  week7/src/components/Modal/KebabFolder.tsx
  week7/src/components/Modal/Modal.tsx
  week7/src/components/Modal/ModalDelete.tsx
  week7/src/components/Modal/ModalEdit.tsx
  week7/src/components/Modal/ModalFolderAdd.tsx
  week7/src/components/Modal/ModalLinkAdd.tsx
  week7/src/components/Modal/ModalShare.tsx
  week7/src/custom.d.ts
  week7/src/hooks/useFetch.js
  week7/src/hooks/useFetch.tsx
  week7/src/index.jsx
  week7/tsconfig.json
Labels: 매운맛🔥, 순한맛🐑 

#843 [한태욱] Week13
  .eslintrc.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/App.tsx
  src/api/BaseUrl.ts
  src/components/AddLink.tsx
  src/components/Card.tsx
  src/components/CardList.tsx
  src/components/Category.tsx
  src/components/CategoryList.tsx
  src/components/Folder.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Modal/Add.tsx
  src/components/Modal/AddFolder.tsx
  src/components/Modal/DeleteFolder.tsx
  src/components/Modal/DeleteLink.tsx
  src/components/Modal/EditFolder.tsx
  src/components/Modal/Share.tsx
  src/components/Popover.tsx
  src/components/SearchBar.tsx
  src/components/folder.js
  src/components/info.tsx
  src/index.tsx
  src/pages/FolderPage.js
  src/pages/FolderPage.tsx
  src/pages/MainPage.tsx
  src/pages/SharedPage.js
  src/pages/SharedPage.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/styles/AddLink.css
  tsconfig.json
Labels: 매운맛🔥, 미완성

#816 [week13] 박우혁
  README.md
  jsconfig.json
  package-lock.json
  package.json
  src/api/GetFolderInfo.tsx
  src/api/GetUserFolder.tsx
  src/api/GetUserInfo.tsx
  src/components/FolderPage/AddFolderInput/AddFolderInput.module.css
  src/components/FolderPage/AddFolderInput/AddFolderInput.tsx
  src/components/FolderPage/CardList/CardList.tsx
  src/components/FolderPage/CardListItem/CardListItem.tsx
  src/components/FolderPage/FolderList/FolderList.tsx
  src/components/FolderPage/FolderListCtrl/FolderListCtrl.tsx
  src/components/FolderPage/FolderListItem/FolderListItem.tsx
  src/components/FolderPage/Footer/Footer.tsx
  src/components/FolderPage/Header/Header.tsx
  src/components/FolderPage/Main/Main.tsx
  src/components/FolderPage/Modal/Modal.module.css
  src/components/FolderPage/Modal/Modal.tsx
  src/components/FolderPage/Nav/Nav.tsx
  src/components/FolderPage/SearchInput/SearchInput.module.css
  src/components/FolderPage/SearchInput/SearchInput.tsx
  src/components/SharedPage/CardList/CardList.tsx
  src/components/SharedPage/CardListItem/CardListItem.tsx
  src/components/SharedPage/Footer/Footer.tsx
  src/components/SharedPage/Header/Header.tsx
  src/components/SharedPage/Main/Main.js
  src/components/SharedPage/Main/Main.tsx
  src/components/SharedPage/Nav/Nav.tsx
  src/components/SharedPage/SearchInput/SearchInput.module.css
  src/components/SharedPage/SearchInput/SearchInput.tsx
  src/hook/useAsync.ts
  src/pages/Folder.js
  src/pages/Rending.tsx
  src/pages/Shared.js
  src/react-app-env.d.ts
  tsconfig.json
Labels: 순한맛🐑 

#853 [이유승] Week13
  README.md
  index.d.ts
  package-lock.json
  package.json
  src/API/App.tsx
  src/API/FolderPageApi.js
  src/API/FolderPageApi.tsx
  src/API/Main.tsx
  src/API/SharedPageApi.tsx
  src/Assets/image/Search.svg
  src/Assets/image/close.svg
  src/Assets/image/defaultImg.svg
  src/Assets/image/delete.svg
  src/Assets/image/facebook.svg
  src/Assets/image/instagram.svg
  src/Assets/image/kebab.svg
  src/Assets/image/link.svg
  src/Assets/image/logo.svg
  src/Assets/image/pen.svg
  src/Assets/image/share.svg
  src/Assets/image/star.svg
  src/Assets/image/twitter.svg
  src/Assets/image/youtube.svg
  src/Components/Button.js
  src/Components/Button.tsx
  src/Components/FolderCard.tsx
  src/Components/FolderHeader.js
  src/Components/FolderHeader.tsx
  src/Components/FolderMain.tsx
  src/Components/FolderMenu.js
  src/Components/FolderMenu.tsx
  src/Components/FolderTools.js
  src/Components/FolderTools.tsx
  src/Components/Footer.js
  src/Components/Footer.tsx
  src/Components/Modal/ModalAddFolder.tsx
  src/Components/Modal/ModalAddLink.tsx
  src/Components/Modal/ModalContainer.tsx
  src/Components/Modal/ModalDeleteFolder.tsx
  src/Components/Modal/ModalEdit.tsx
  src/Components/Nav.tsx
  src/Components/SharedCard.tsx
  src/Components/SharedHeader.tsx
  src/Components/SharedMain.tsx
  src/Hooks/useFolder.js
  src/Hooks/useFolder.tsx
  src/Hooks/useFolderName.js
  src/Hooks/useFolderName.tsx
  src/Hooks/useLinks.tsx
  src/Hooks/useModalOpen.tsx
  src/Pages/FolderPage.tsx
  src/Pages/SharedPage.tsx
  src/Styles/FolderHeader.css
  src/Styles/FolderTools.css
  src/index.tsx
  src/react-app-env.d.ts
  tsconfig.json
Labels: 미완성, 순한맛🐑 

#832 [최원석] Week13
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/api/api.ts
  src/components/AddLinkBar.module.css
  src/components/AddLinkBar.tsx
  src/components/BottomNavBar.tsx
  src/components/Card.module.css
  src/components/Card.tsx
  src/components/CardBox.tsx
  src/components/EmptyFolder.tsx
  src/components/FolderButton.tsx
  src/components/FolderListBar.module.css
  src/components/FolderListBar.tsx
  src/components/FolderOptions.jsx
  src/components/FolderOptions.tsx
  src/components/HeaderFrame.tsx
  src/components/Icon.tsx
  src/components/SearchBar.jsx
  src/components/SearchBar.module.css
  src/components/SearchBar.tsx
  src/components/SelectMenu.tsx
  src/components/TopNavBar.tsx
  src/components/UserProfile.tsx
  src/hooks/useIntersectionObserver.ts
  src/hooks/useSearchBar.ts
  src/index.tsx
  src/modal/AddFolderModal/AddFolderModal.tsx
  src/modal/AddToFolderModal/AddToFolderModal.tsx
  src/modal/AddToFolderModal/FolderInModal.tsx
  src/modal/DeleteFolderModal/DeleteFolderModal.tsx
  src/modal/DeleteLinkModal/DeleteLinkModal.tsx
  src/modal/EditModal/EditModal.tsx
  src/modal/ModalLayout.tsx
  src/modal/ShareModal/ShareModal.tsx
  src/pages/AppFrame.css
  src/pages/AppFrame.tsx
  src/pages/Folder.jsx
  src/pages/Folder.tsx
  src/pages/Shared.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/types/commonTypes.ts
  src/util/copyClipBoard.ts
  src/util/datecalc.ts
  tsconfig.json
Labels: 매운맛🔥

#844 [김경주] Week13
  package-lock.json
  package.json
  public/img/_close.svg
  src/components/App.js
  src/components/App.tsx
  src/components/Card.tsx
  src/components/CardList.tsx
  src/components/FolderCardList.js
  src/components/FolderCardList.tsx
  src/components/FolderHeader.tsx
  src/components/FolderList.tsx
  src/components/FolderMain.tsx
  src/components/FolderProfile.tsx
  src/components/Footer.js
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Main.tsx
  src/components/Profile.tsx
  src/index.js
  src/index.tsx
  src/pages/folder.tsx
  src/pages/home.tsx
  src/pages/shared.tsx
  src/styles/cardlist.css
  src/styles/foldercardlist.css
  src/utils/timeCalc.tsx
  tsconfig.json
Labels: 순한맛🐑 

#812 [최준영] week13
  .gitignore
  README.md
  package-lock.json
  package.json
  public/_redirects
  src/Main.tsx
  src/api.ts
  src/components/Card.js
  src/components/Cardfolder.js
  src/components/Folder.js
  src/components/Footer.js
  src/components/Footer.tsx
  src/components/HomePage.js
  src/components/Main.js
  src/components/Mainfolder.js
  src/components/Mainpage/MainHome.tsx
  src/components/Shared.js
  src/components/folderpage/Cardfolder.tsx
  src/components/folderpage/FolderList.tsx
  src/components/folderpage/Gnbfolder.tsx
  src/components/folderpage/Headerfolder.tsx
  src/components/folderpage/LinkInput.tsx
  src/components/folderpage/Mainfolder.tsx
  src/components/sharedpage/Card.tsx
  src/components/sharedpage/Header.tsx
  src/components/sharedpage/Main.tsx
  src/consts/const.ts
  src/consts/type.ts
  src/css/main.css
  src/hooks/useComponentVisible.tsx
  src/index.js
  src/index.tsx
  src/modals/Add.tsx
  src/modals/Delete.tsx
  src/modals/Edit.tsx
  src/modals/List.tsx
  src/modals/Share.tsx
  src/pages/Folder.tsx
  src/pages/HomePage.tsx
  src/pages/Shared.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/utils/fetchApi.ts
  src/utils/setTime.js
  src/utils/setTime.ts
  tsconfig.json
Labels: 매운맛🔥

#835 [김예진] Week13
  package-lock.json
  package.json
  src/App.tsx
  src/Main.tsx
  src/api.ts
  src/assets/icons/cancel.svg
  src/assets/styles/AddLinkBar.css
  src/assets/styles/Navbar.css
  src/assets/styles/Page.css
  src/assets/styles/SearchBar.css
  src/components/Folder/AddLinkBar.tsx
  src/components/Folder/FolderCardItem.tsx
  src/components/Folder/FolderCardList.tsx
  src/components/Folder/FolderList.tsx
  src/components/Shared/CardItem.tsx
  src/components/Shared/CardList.tsx
  src/components/Shared/Header.tsx
  src/components/common/Footer.tsx
  src/components/common/ModalPortal.js
  src/components/common/ModalPortal.ts
  src/components/common/Navbar.tsx
  src/components/common/SearchBar.js
  src/components/common/SearchBar.tsx
  src/components/hooks/useAsync.js
  src/components/hooks/useAsync.ts
  src/components/modal/AddFolderModal.tsx
  src/components/modal/AddLinkModal.tsx
  src/components/modal/DeleteFolderModal.tsx
  src/components/modal/DeleteLinkModal.tsx
  src/components/modal/Modal.tsx
  src/components/modal/RenameFolderModal.tsx
  src/components/modal/ShareFolderModal.tsx
  src/index.js
  src/index.tsx
  src/pages/FolderPage.js
  src/pages/FolderPage.tsx
  src/pages/SharedPage.js
  src/pages/SharedPage.tsx
  src/react-app-env.d.ts
  src/utils/KakaoShare.tsx
  src/utils/caculateTime.js
  src/utils/caculateTime.ts
  src/utils/formatDate.ts
  tsconfig.json
Labels: 매운맛🔥

#845 [김민정] Week13
  jsconfig.json
  package-lock.json
  package.json
  src/api/api.ts
  src/assets/icons/delete.svg
  src/components/Folder/FolderInput.js
  src/components/Folder/FolderInput.tsx
  src/components/Folder/FolderTitle.tsx
  src/components/Folder/Menus.tsx
  src/components/common/BlueButton.tsx
  src/components/common/FolderItem.tsx
  src/components/common/FolderList.tsx
  src/components/common/FooterElement.tsx
  src/components/common/GlobalStyle.ts
  src/components/common/HeaderElement.tsx
  src/components/common/Input.js
  src/components/common/Input.tsx
  src/components/common/RedButton.tsx
  src/components/common/modals/AddFolderModal.tsx
  src/components/common/modals/AddToFolder.tsx
  src/components/common/modals/DeleteModal.tsx
  src/components/common/modals/EditNameModal.tsx
  src/components/common/modals/PopOver.tsx
  src/components/common/modals/SharedModal.tsx
  src/components/home/CardFrame.tsx
  src/components/home/Headline.tsx
  src/components/shared/SharedSection.tsx
  src/constants/colors.ts
  src/constants/errorMsg.ts
  src/custom.d.ts
  src/hooks/uesGetPromise.ts
  src/pages/Folder.js
  src/pages/Folder.tsx
  src/pages/Home.tsx
  src/pages/Shared.js
  src/pages/Shared.tsx
  tsconfig.json
Labels: 매운맛🔥

#836 [유아름] Week 13
  package-lock.json
  package.json
  public/index.html
  src/components/AddLinkInput/AddLinkInput.jsx
  src/components/Button/Button.jsx
  src/components/Card/Card.module.css
  src/components/Card/EditableCard.jsx
  src/components/DefaultModal/Backdrop.module.scss
  src/components/DefaultModal/Backdrop.tsx
  src/components/DefaultModal/DefaultModal.module.scss
  src/components/DefaultModal/index.tsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Dropdown/index.tsx
  src/components/FolderLinks/FolderLinks.module.css
  src/components/FolderToolBar/FolderAddButton.tsx
  src/components/FolderToolBar/FolderEditBar.jsx
  src/components/FolderToolBar/FolderList.module.css
  src/components/FolderToolBar/FolderToolBar.jsx
  src/components/FolderToolBar/FolderToolBar.module.scss
  src/costom.d.ts
  src/page/FolderPage.jsx
  src/page/FolderPage.module.css
  src/style.d.ts
  tsconfig.json
Labels: 매운맛🔥, 미완성

#877 [심민보] week13
  @types/global/index.d.ts
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/api/api.ts
  src/componenets/Card.tsx
  src/componenets/CardList.jsx
  src/componenets/CardList.tsx
  src/componenets/FloatingActionButton.tsx
  src/componenets/FolderDetail.tsx
  src/componenets/Footer.tsx
  src/componenets/LinkAdd.tsx
  src/componenets/Nav.tsx
  src/componenets/NoLink.tsx
  src/componenets/SearchBar.css
  src/componenets/SearchBar.jsx
  src/componenets/SearchBar.tsx
  src/componenets/modal/AddAtFolder.tsx
  src/componenets/modal/AddFolder.tsx
  src/componenets/modal/DeleteFolder.tsx
  src/componenets/modal/DeleteLink.tsx
  src/componenets/modal/EditFolderName.tsx
  src/componenets/modal/Modal.tsx
  src/componenets/modal/SharedFolder.tsx
  src/constants/sns.ts
  src/hooks/useFetchData.ts
  src/images/_close.svg
  src/index.js
  src/index.tsx
  src/pages/Folder.tsx
  src/pages/Main.tsx
  src/pages/Shared.jsx
  src/pages/Shared.tsx
  src/util/date.ts
  tsconfig.json
Labels: 매운맛🔥, 미완성

#855 [김혜중] Week13
  .env.sample
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/api.ts
  src/components/Account/index.tsx
  src/components/CardGrid/Cardgrid.js
  src/components/CardGrid/Cardgrid.jsx
  src/components/CardGrid/Utils/useCardData.ts
  src/components/CardGrid/Utils/utils.ts
  src/components/Common/Footer.tsx
  src/components/Common/Nav.tsx
  src/components/FolderContent/LinkCategory/index.tsx
  src/components/FolderContent/NoLink.tsx
  src/components/HeaderFolder/index.tsx
  src/components/LinkForm/index.js
  src/components/LinkForm/index.scss
  src/components/LinkForm/index.tsx
  src/components/Modal/AddFolder.jsx
  src/components/Modal/AddFolder.tsx
  src/components/Modal/AddToFolder.tsx
  src/components/Modal/ChangeName.tsx
  src/components/Modal/DeleteFolder.tsx
  src/components/Modal/DeleteLink.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/Portal.jsx
  src/components/Modal/Portal.tsx
  src/components/Modal/ShareLink.tsx
  src/components/Modal/addChange.module.scss
  src/components/Modal/addToFolder.module.scss
  src/components/Modal/delete.module.scss
  src/components/Modal/shareKakao.tsx
  src/components/Modal/shareLink.module.scss
  src/components/Search/Search.css
  src/components/Search/Search.js
  src/components/Search/Search.tsx
  src/custom.d.ts
  src/global.d.ts
  src/image/Kakao.svg
  src/image/check.svg
  src/image/close.svg
  src/image/library.png
  src/image/share_facebook.svg
  src/image/share_link.svg
  src/pages/folder.js
  src/pages/folder.scss
  src/pages/folder.tsx
  src/pages/main.tsx
  src/pages/shared.tsx
  src/style/reset.css
  src/types/interface.ts
  tsconfig.json
Labels: 매운맛🔥

#867 Part2 황경수 week13
  package-lock.json
  package.json
  src/Main.tsx
  src/api.tsx
  src/components/App.tsx
  src/components/Modal/FolderAddList.tsx
  src/components/Modal/ModalBase.tsx
  src/components/Modal/ModalWithInput.tsx
  src/components/Modal/ShareSnsList.tsx
  src/components/common/Backdrop.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/SearchBar.tsx
  src/components/folder/AddLink.tsx
  src/components/folder/Dropdown.tsx
  src/components/folder/FoderOptionMenu.tsx
  src/components/folder/FolderButton.tsx
  src/components/folder/FolderInfo.tsx
  src/components/folder/FolderTitle.tsx
  src/components/hooks/useAsync.js
  src/components/hooks/useAsync.ts
  src/components/shared/Card.tsx
  src/components/shared/CardList.tsx
  src/components/shared/SharedInfo.tsx
  src/custom.d.ts
  src/pages/Folder.tsx
  src/pages/HomaPage.tsx
  src/pages/Shared.jsx
  src/pages/Shared.tsx
  src/text.bat
  tsconfig.json
Labels: 매운맛🔥

#868 [신민철] Week13
  README.md
  package-lock.json
  package.json
  src/@types/Img.d.ts
  src/@types/index.d.ts
  src/App.tsx
  src/components/Card.tsx
  src/components/Folder.js
  src/components/Folder.tsx
  src/components/Shared.tsx
  src/components/modal/AddFolderModal.tsx
  src/components/modal/AddLinkModal.tsx
  src/components/modal/DeleteFolderModal.tsx
  src/components/modal/DeleteLinkModal.tsx
  src/components/modal/EditModal.tsx
  src/components/modal/ShareModal.tsx
  src/index.tsx
  tsconfig.json
  yarn.lock
Labels: 매운맛🔥

#849 [손승현] Week 13
  public/images/close.png
  public/index.html
  src/components/AddLinkBar/AddLinkBar.css
  src/components/AddLinkBar/AddLinkBar.jsx
  src/components/EmptyLink/EmptyLink.css
  src/components/Footer/Footer.jsx
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.jsx
  src/hooks/useGetFolderLinks.js
  src/hooks/useGetFolderLists.js
  src/layout/Layout.jsx
  src/pages/MainFolderPage/MainFolderPage.jsx
  src/pages/MainSharePage/MainSharePage.jsx
Labels: 매운맛🔥, 미완성

#831 [정봉찬] Week13
  package-lock.json
  package.json
  src/App.tsx
  src/api.ts
  src/components/Button/Button.tsx
  src/components/Button/index.ts
  src/components/Card/Card.tsx
  src/components/Card/CardList.tsx
  src/components/Card/index.ts
  src/components/Icon/index.ts
  src/components/Icon/svg/IconAdd.tsx
  src/components/Icon/svg/IconDustbin.tsx
  src/components/Icon/svg/IconKebabMenu.tsx
  src/components/Icon/svg/IconLink.tsx
  src/components/Icon/svg/IconLogo.tsx
  src/components/Icon/svg/IconPen.tsx
  src/components/Icon/svg/IconSearch.tsx
  src/components/Icon/svg/IconShare.tsx
  src/components/Icon/svg/IconStar.tsx
  src/components/Icon/svg/sns/IconFacebook.tsx
  src/components/Icon/svg/sns/IconInstagram.tsx
  src/components/Icon/svg/sns/IconTwitter.tsx
  src/components/Icon/svg/sns/IconYoutube.tsx
  src/components/Layout/Footer/Footer.tsx
  src/components/Layout/Footer/index.ts
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Header/index.ts
  src/components/Layout/Layout.tsx
  src/components/Layout/index.ts
  src/components/SearchBox/SearchBox.tsx
  src/components/SearchBox/SearchBoxLink.styled.tsx
  src/components/SearchBox/SearchBoxLink.tsx
  src/components/SearchBox/index.ts
  src/components/Tab/Tab.jsx
  src/components/Tab/Tab.tsx
  src/components/Tab/TabList.tsx
  src/components/Tab/index.ts
  src/components/Tab/styles/Tab.styled.tsx
  src/components/Tab/styles/TabList.styled.tsx
  src/contexts/LoginContext.tsx
  src/index.tsx
  src/pages/Folder/FolderPage.styled.tsx
  src/pages/Folder/FolderPage.tsx
  src/pages/Landing/LandingPage.tsx
  src/pages/Shared/SharedPage.tsx
  src/react-app-env.d.ts
  src/types/common.ts
  src/utils/date.ts
  tsconfig.json
Labels: 매운맛🔥, 미완성
