Repository codeit-bootcamp-frontend/4-Weekly-Mission, pull requests merged in 2024-01, with the labels that each got.

#12 [문지혜] Week2
  .DS_Store
  .vscode/launch.json
  assets/main.png
  assets/signIn.png
  assets/signUp.png
  faq.html
  index.html
  privacy.html
  public/images/landing/icons/facebook.png
  public/images/landing/icons/instagram.png
  public/images/landing/icons/twitter.png
  public/images/landing/icons/youtube.png
  public/images/landing/landing-logo.png
  public/images/landing/main-image.png
  public/images/landing/section1-card1.png
  public/images/landing/section1-card2.png
  public/images/landing/section1-card3.png
  public/images/landing/section1-icon.png
  public/images/landing/section2-card.png
  public/images/landing/section3-cover.png
  public/images/landing/section3-share.png
  public/images/landing/section4.png
  public/images/sign/signup-eye-on.svg
  sign.css
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#13 [김인석] Week2
  weekly-mission(week2)/css/index.css
  weekly-mission(week2)/css/signin.css
  weekly-mission(week2)/images/asd.svg
  weekly-mission(week2)/images/eye-off.svg
  weekly-mission(week2)/images/eye-on.svg
  weekly-mission(week2)/images/facebook.svg
  weekly-mission(week2)/images/google-sns.svg
  weekly-mission(week2)/images/instagram.svg
  weekly-mission(week2)/images/kakao-sns.svg
  weekly-mission(week2)/images/logo.svg
  weekly-mission(week2)/images/sec1.svg
  weekly-mission(week2)/images/sec2.svg
  weekly-mission(week2)/images/sec3.svg
  weekly-mission(week2)/images/sec4.svg
  weekly-mission(week2)/images/title-img.png
  weekly-mission(week2)/images/title-img.svg
  weekly-mission(week2)/images/twitter.svg
  weekly-mission(week2)/images/youtube.svg
  weekly-mission(week2)/index.html
  weekly-mission(week2)/signin.html
  weekly-mission(week2)/signup.html
Labels: 매운맛🔥

#23 [황준용]week3
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
Labels: 매운맛🔥

#38 Create README.md
  README.md
Labels: help wanted

#40 Revert "Create README.md"
  README.md
Labels: 순한맛🐑 

#30 [권나은]Week3
  .gitignore
  img/Card-1.png
  img/Card-2.png
  img/Card-3.png
  img/Card-4.png
  img/Card-5.png
  img/Card-6.png
  img/Card-7.png
  img/Card-8.png
  img/Card-9.png
  img/Card.png
  img/google.png
  img/kakaotalk.png
  index.html
  landing/_img1.png
  landing/_img4.png
  landing/image 25.png
  landing/img2.png
  landing/img3.png
  loginin.css
  loginin.html
  mainpage.css
  signup.css
  signup.html
Labels: 매운맛🔥

#55 [강나리] week3
  images/eye-off.svg
  images/facebook.svg
  images/folder_image.svg
  images/google_logo.png
  images/instagram.svg
  images/kakao_logo.png
  images/link_image.svg
  images/logo.svg
  images/main_image.png
  images/main_image.svg
  images/search_image.svg
  images/share_image.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  signin.html
  signup.html
  styles/signin.css
  styles/signup.css
  styles/style.css
Labels: 순한맛🐑 

#41 [남현준] week3
  .github/pull_request_template.md
  .gitignore
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
Labels: 매운맛🔥

#97 [박유빈]Week3
  .vscode/settings.json
  2주차/home/home.css
  2주차/home/home.html
  2주차/home/icon/landing/akar-icons_facebook-fill.svg
  2주차/home/icon/landing/akar-icons_twitter-fill.svg
  2주차/home/icon/landing/akar-icons_youtube-fill.svg
  2주차/home/icon/landing/ant-design_instagram-filled.svg
  2주차/home/image/color.png
  2주차/home/image/dog.png
  2주차/home/image/folder.png
  2주차/home/image/mood.png
  2주차/home/image/page.png
  2주차/home/image/search.png
  2주차/home/image/share.png
  2주차/home/logo.svg
  2주차/join/image/google.png
  2주차/join/image/kakao.svg
  2주차/join/join.css
  2주차/join/join.html
  2주차/join/signin/icon/google.svg
  2주차/join/signin/icon/kakao.svg
  2주차/join/signin/logo.svg
  2주차/join/signup/eye-on.svg
  2주차/login/image/google.png
  2주차/login/image/kakao.svg
  2주차/login/login.css
  2주차/login/login.html
  2주차/login/signin/icon/google.svg
  2주차/login/signin/icon/kakao.svg
  2주차/login/signin/logo.svg
  3주차/home/home.css
  3주차/home/home.html
  3주차/home/icon/landing/akar-icons_facebook-fill.svg
  3주차/home/icon/landing/akar-icons_twitter-fill.svg
  3주차/home/icon/landing/akar-icons_youtube-fill.svg
  3주차/home/icon/landing/ant-design_instagram-filled.svg
  3주차/home/image/dog.png
  3주차/home/image/folder.png
  3주차/home/image/page.png
  3주차/home/image/search.png
  3주차/home/image/share.png
  3주차/home/logo.svg
  3주차/join/image/google.png
  3주차/join/image/kakao.svg
  3주차/join/join.css
  3주차/join/join.html
  3주차/join/signin/icon/google.svg
  3주차/join/signin/icon/kakao.svg
  3주차/join/signin/logo.svg
  3주차/join/signup/eye-on.svg
  3주차/login/image/google.png
  3주차/login/image/kakao.svg
  3주차/login/login.css
  3주차/login/login.html
  3주차/login/signin/icon/google.svg
  3주차/login/signin/icon/kakao.svg
  3주차/login/signin/logo.svg
Labels: 매운맛🔥, 미완성

#29 [차수지] Week3
  .gitignore
  .vscode/settings.json
  assets/.DS_Store
  assets/common/logo.svg
  assets/landing/.DS_Store
  assets/landing/content-1.png
  assets/landing/content-2.png
  assets/landing/content-3.png
  assets/landing/content-4.png
  assets/landing/content-5.png
  assets/landing/ic-facebook.svg
  assets/landing/ic-instagram.svg
  assets/landing/ic-twitter.svg
  assets/landing/ic-youtube.svg
  assets/sign/eye.svg
  assets/sign/google.png
  assets/sign/kakao.png
  assets/sign/kakao.svg
  css/colors.css
  css/global.css
  css/landing.css
  css/reset.css
  css/sign.css
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥

#83 [김재영]Week3
  icons/eyesoff.png
  icons/eyeson.png
  imgs/contents1.png
  imgs/contents2.png
  imgs/contents3.png
  imgs/contents4.png
  imgs/goolge-logo.png
  imgs/main-img.png
  index.html
  sign.css
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#91 [김보경]week3
  README.md
  img/link.png
  img/linkmanage.png
  img/main-container.png
  img/search.png
  img/share.png
  index.html
  reset.css
  signin/google.png
  signin/index.html
  signin/kakao.png
  signin/style.css
  signup/google.png
  signup/index.html
  signup/kakao.png
  signup/style.css
  style.css
Labels: 매운맛🔥

#75 [이재빈]Week3
  .gitignore
  1-weekly-mission-week2-main/.gitignore
  1-weekly-mission-week2-main/faq.html
  1-weekly-mission-week2-main/images/eye-off.svg
  1-weekly-mission-week2-main/images/facebook.svg
  1-weekly-mission-week2-main/images/google.png
  1-weekly-mission-week2-main/images/hero.png
  1-weekly-mission-week2-main/images/image1.png
  1-weekly-mission-week2-main/images/image2.png
  1-weekly-mission-week2-main/images/image3.png
  1-weekly-mission-week2-main/images/image4.png
  1-weekly-mission-week2-main/images/instagram.svg
  1-weekly-mission-week2-main/images/kakao.svg
  1-weekly-mission-week2-main/images/library.jpg
  1-weekly-mission-week2-main/images/logo.svg
  1-weekly-mission-week2-main/images/twitter.svg
  1-weekly-mission-week2-main/images/youtube.svg
  1-weekly-mission-week2-main/index.html
  1-weekly-mission-week2-main/privacy.html
  1-weekly-mission-week2-main/signin.html
  1-weekly-mission-week2-main/signup.html
  1-weekly-mission-week2-main/src/colors.css
  1-weekly-mission-week2-main/src/global.css
  1-weekly-mission-week2-main/src/landing.css
  1-weekly-mission-week2-main/src/reset.css
  1-weekly-mission-week2-main/src/sign.css
  __MACOSX/._1-weekly-mission-week2-main
  __MACOSX/1-weekly-mission-week2-main/._.gitignore
  __MACOSX/1-weekly-mission-week2-main/._faq.html
  __MACOSX/1-weekly-mission-week2-main/._images
  __MACOSX/1-weekly-mission-week2-main/._index.html
  __MACOSX/1-weekly-mission-week2-main/._privacy.html
  __MACOSX/1-weekly-mission-week2-main/._signin.html
  __MACOSX/1-weekly-mission-week2-main/._signup.html
  __MACOSX/1-weekly-mission-week2-main/._src
  __MACOSX/1-weekly-mission-week2-main/images/._eye-off.svg
  __MACOSX/1-weekly-mission-week2-main/images/._facebook.svg
  __MACOSX/1-weekly-mission-week2-main/images/._google.png
  __MACOSX/1-weekly-mission-week2-main/images/._hero.png
  __MACOSX/1-weekly-mission-week2-main/images/._image1.png
  __MACOSX/1-weekly-mission-week2-main/images/._image2.png
  __MACOSX/1-weekly-mission-week2-main/images/._image3.png
  __MACOSX/1-weekly-mission-week2-main/images/._image4.png
  __MACOSX/1-weekly-mission-week2-main/images/._instagram.svg
  __MACOSX/1-weekly-mission-week2-main/images/._kakao.svg
  __MACOSX/1-weekly-mission-week2-main/images/._logo.svg
  __MACOSX/1-weekly-mission-week2-main/images/._twitter.svg
  __MACOSX/1-weekly-mission-week2-main/images/._youtube.svg
  __MACOSX/1-weekly-mission-week2-main/src/._colors.css
  __MACOSX/1-weekly-mission-week2-main/src/._global.css
  __MACOSX/1-weekly-mission-week2-main/src/._landing.css
  __MACOSX/1-weekly-mission-week2-main/src/._reset.css
  __MACOSX/1-weekly-mission-week2-main/src/._sign.css
Labels: 매운맛🔥

#77 [정사비비] Week3
  faq.html
  image/eye-off.svg
  image/eye-on.svg
  image/facebook.svg
  image/google_login.svg
  image/hero.png
  image/img1.png
  image/img2.png
  image/img3.png
  image/img4.png
  image/insta.svg
  image/kakao_login.svg
  image/logo.svg
  image/twitter.svg
  image/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/color.css
  src/global.css
  src/reset.css
  src/signin-style.css
  src/signup-style.css
  src/style.css
Labels: 순한맛🐑 

#113 [김주원] week2
  css/color.css
  css/landing.css
  css/signin.css
  css/signup.css
  html/Privacy.html
  html/faq.html
  html/landing.html
  html/signin.html
  html/signup.html
  img/Ellipse 22.svg
  img/card-download-icon.svg
  img/eye-off.svg
  img/eye-on.svg
  img/facebook icon.jpg
  img/folder name change.png
  img/folder share.png
  img/google icon back.svg
  img/google icon.png
  img/instagram icon.jpg
  img/kakao icon back.svg
  img/kakao icon.svg
  img/link-card-bed.png
  img/link-card-dog.png
  img/link-card-gradient.png
  img/link_page_collection.png
  img/logo.svg
  img/search codeit.png
  img/twitter icon.jpg
  img/youtube icon.jpg
Labels: 매운맛🔥, 미완성

#87 [소남주] Week3
  .vscode/settings.json
  faq/faq_style.css
  faq/index.html
  images/banner_image.png
  images/content_1.png
  images/content_2.png
  images/content_3.png
  images/content_4.png
  images/eye_off.svg
  images/facebook.svg
  images/google_background.svg
  images/google_icon.png
  images/instagram.svg
  images/kakaotalk_background.svg
  images/kakaotalk_icon.svg
  images/logo.svg
  images/logo_big.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  login/index.html
  login/login_style.css
  privacy/index.html
  privacy/privacy_style.css
  signup/index.html
  signup/signup_style.css
  style.css
Labels: 매운맛🔥

#70 [황경수] week3
  CSS/landing/footer.css
  CSS/landing/header.css
  CSS/landing/main.css
  CSS/palette.css
  CSS/sign/sign.css
  assets/images/banner.png
  assets/images/content1.png
  assets/images/content2.png
  assets/images/content3.png
  assets/images/content4.png
  assets/images/google-login.png
  assets/images/kakao-login.png
  assets/svg/eye-off.svg
  assets/svg/facebook.svg
  assets/svg/instagram.svg
  assets/svg/logo.svg
  assets/svg/store.svg
  assets/svg/twitter.svg
  assets/svg/youtube.svg
  faq/index.html
  index.html
  privacy/index.html
  signin/index.html
  signup/index.html
  style.css
Labels: 매운맛🔥

#94 [신민철] Week3
  README.md
  css/global.css
  css/landing.css
  css/signin.css
  css/signup.css
  faq.html
  images/Landingimg.png
  images/card.png
  images/eye-off.svg
  images/eye-on.svg
  images/facebook.svg
  images/google.svg
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/pop-up.png
  images/pop-up2.png
  images/pop-up3.png
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#32 [김재성] week3
  .gitignore
  css/config.css
  css/index.css
  faq/index.html
  images/eye-off.png
  images/eye-on.png
  images/haeder-image.png
  images/login-logo.png
  images/logo.png
  images/main-img1.png
  images/main-img2.png
  images/main-img3.png
  images/main-img4.png
  images/og_image.jpeg
  images/sns-facebook.png
  images/sns-google.png
  images/sns-instargram.png
  images/sns-kakao.png
  images/sns-twitter.png
  images/sns-youtube.png
  index.html
  js/index.js
  privacy/index.html
  signin/css/signin.css
  signin/index.html
  signin/js/signin.js
  signup/css/signup.css
  signup/index.html
  signup/js/signup.js
Labels: 매운맛🔥

#105 [김동현] Week3
  .github/pull_request_template.md
  images/Component 2.png
  images/Component 3.png
  images/akar-icons_facebook-fill.svg
  images/akar-icons_twitter-fill.svg
  images/akar-icons_youtube-fill.svg
  images/ant-design_instagram-filled.svg
  images/eye-off.svg
  images/img.png
  images/img1.png
  images/img2.png
  images/img3.png
  images/img4.png
  images/library.png
  images/logo.svg
  images/sign_logo.svg
  index.html
  signin.html
  signup.html
  src/landing.css
  src/sign.css
  workflows/delete-merged-branch-config.yml
Labels: 매운맛🔥

#50 [유아름] WEEK3
  faq/index.html
  images/linkbrary_content_folder.png
  images/linkbrary_content_link.png
  images/linkbrary_content_search.png
  images/linkbrary_content_share.png
  images/linkbrary_key_screen.png
  images/logo.svg
  index.html
  privacy/index.html
  signin/index.html
  signup/index.html
  style.css
  styles/common.css
  styles/fonts/icomoon.eot
  styles/fonts/icomoon.svg
  styles/fonts/icomoon.ttf
  styles/fonts/icomoon.woff
  styles/login-page.css
  styles/reset.css
Labels: 매운맛🔥

#92 [여승구] week3
  faq.html
  images/download.svg
  images/eye-off.svg
  images/facebook.svg
  images/google-background.svg
  images/google.png
  images/instagram.svg
  images/kakaotalk-background.svg
  images/kakaotalk.svg
  images/logo.svg
  images/main.png
  images/popup-download.png
  images/popup-fix.png
  images/popup-search.png
  images/popup-share.png
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/common.css
  src/reset.css
  src/sign.css
  src/style.css
Labels: 매운맛🔥, 미완성

#73 [김태진] week3
  assets/Linkbrary.png
  assets/eye-off.svg
  assets/eye-on.svg
  assets/facebook.svg
  assets/google.png
  assets/header-cover.png
  assets/header-logo.svg
  assets/instagram.svg
  assets/kakao.svg
  assets/main-cover01.png
  assets/main-cover02.png
  assets/main-cover03.png
  assets/main-cover04.png
  assets/twitter.svg
  assets/youtube.svg
  css/color.css
  css/commons.css
  css/form.css
  css/reset.css
  css/typography.css
  faq/index.html
  index.css
  index.html
  privacy/index.html
  signin/index.html
  signup/index.html
Labels: 순한맛🐑 

#99 [박우혁] week3
  위클리과제/image/eye.svg
  위클리과제/image/facebook.png
  위클리과제/image/google.png
  위클리과제/image/insta.png
  위클리과제/image/kakao.svg
  위클리과제/image/logo.svg
  위클리과제/image/mainimg.png
  위클리과제/image/section1.png
  위클리과제/image/section2.png
  위클리과제/image/section3.png
  위클리과제/image/section4.png
  위클리과제/image/twitter.png
  위클리과제/image/youtube.png
  위클리과제/index.css
  위클리과제/index.html
  위클리과제/signin.css
  위클리과제/signin.html
  위클리과제/signup.css
  위클리과제/signup.html
Labels: 미완성

#134 위클리과제3주차
  week2summary/week2summary/img/indeximg/1img.jpg
  week2summary/week2summary/img/indeximg/a-logo.svg
  week2summary/week2summary/img/indeximg/c1.png
  week2summary/week2summary/img/indeximg/c2.png
  week2summary/week2summary/img/indeximg/c3.png
  week2summary/week2summary/img/indeximg/c4.png
  week2summary/week2summary/img/indeximg/facebook-icon.svg
  week2summary/week2summary/img/indeximg/instagram-icon.svg
  week2summary/week2summary/img/indeximg/twitter-icon.svg
  week2summary/week2summary/img/indeximg/youtube-icon.svg
  week2summary/week2summary/img/signupimg/google.svg
  week2summary/week2summary/img/signupimg/kakaotalk.svg
  week2summary/week2summary/img/signupimg/logo.svg
  week2summary/week2summary/index.html
  week2summary/week2summary/signin.css
  week2summary/week2summary/signin.html
  week2summary/week2summary/signup.css
  week2summary/week2summary/signup.html
  week2summary/week2summary/style.css
Labels: 매운맛🔥

#141 [김재영]Week3
  icons/eyesoff.png
  icons/eyeson.png
  imgs/contents1.png
  imgs/contents2.png
  imgs/contents3.png
  imgs/contents4.png
  imgs/goolge-logo.png
  imgs/main-img.png
  index.html
  sign.css
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#108 [양서연] Week3
  css/Linkbrary_style.css
  css/palette.css
  css/signin_style.css
  css/signup_style.css
  faq.html
  images/99FE484C5C3451F218 1.svg
  images/Component 2.png
  images/Component 3.png
  images/_img1.png
  images/_img4.png
  images/akar-icons_facebook-fill.svg
  images/akar-icons_twitter-fill.svg
  images/akar-icons_youtube-fill.svg
  images/ant-design_instagram-filled.svg
  images/eye-off.svg
  images/eye-on.svg
  images/hero.png
  images/img2.png
  images/img3.png
  images/logo.svg
  images/preview.png
  index.html
  privacy.html
  signin.html
  signup.html
Labels: 미완성, 순한맛🐑 

#36 [문지혜] Week3
  .DS_Store
  assets/.DS_Store
  assets/meta.png
  index.html
  index.js
  public/images/landing/section1-card1.png
  public/images/landing/section1-card2.png
  public/images/landing/section1-card3.png
  public/images/landing/section1-icon.png
  public/images/landing/section1.png
  public/images/landing/section2-card.png
  public/images/landing/section2.png
  public/images/landing/section3-cover.png
  public/images/landing/section3-share.png
  public/images/landing/section3.png
  public/images/landing/section4.png
  public/images/sign/kakao.svg
  sign.css
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#126 [윤여진] week3
  .gitignore
  css/color.css
  css/media.css
  css/signin.css
  css/signup.css
  css/style.css
  faq.html
  images/books.jpeg
  images/eye-solid.svg
  images/icon-facebook.png
  images/icon-google.png
  images/icon-instagram.png
  images/icon-kakao.png
  images/icon-twitter.png
  images/icon-youtube.png
  images/logo.png
  images/section-img1.png
  images/section-img2.png
  images/section-img3.png
  images/section-img4.png
  images/topBody-img.png
  index.html
  package-lock.json
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#125 [이지수]week3
  assets_index/_img.png
  assets_index/_img1.png
  assets_index/_img4.png
  assets_index/akar-icons_facebook-fill.svg
  assets_index/akar-icons_twitter-fill.svg
  assets_index/akar-icons_youtube-fill.svg
  assets_index/ant-design_instagram-filled.svg
  assets_index/img2.png
  assets_index/img3.png
  assets_index/logo.svg
  assets_signin/Component 2.svg
  assets_signin/Component 3.svg
  assets_signin/logo.svg
  index.html
  signin.html
  signup.html
  stylesheets/main.css
  stylesheets/reset.css
  stylesheets/signup.css
  stylesheets/style.css
  stylesheets/theme.css
Labels: 미완성, 순한맛🐑 

#51 [김현찬] Week3 위클리 과제
  faq/index.html
  images/Group 20.svg
  images/_dim.svg
  images/_img 1.svg
  images/_img.svg
  images/_img4 1.svg
  images/akar-icons_facebook-fill.svg
  images/akar-icons_twitter-fill.svg
  images/akar-icons_youtube-fill.svg
  images/ant-design_instagram-filled.svg
  images/image 25.svg
  images/img2.svg
  images/img3 1.svg
  images/library-image.jpg
  images/logo.svg
  index.html
  privacy/index.html
  signin/facebook.svg
  signin/images/Component 2.svg
  signin/images/Component 3.svg
  signin/images/logo.svg
  signin/index.html
  signin/style.css
  signinup/images/Component 2.svg
  signinup/images/Component 3.svg
  signinup/images/logo.svg
  signinup/index.html
  signinup/style.css
  style.css
Labels: 미완성

#60 [김효진] Week3 위클리 과제
  .gitignore
  README.md
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
Labels: 순한맛🐑 

#11 [기송은] Week3 위클리 과제
  위클리_미션/faq.html
  위클리_미션/index.html
  위클리_미션/landing_image/Card 1.png
  위클리_미션/landing_image/Card-1.png
  위클리_미션/landing_image/Card.png
  위클리_미션/landing_image/Group 20.png
  위클리_미션/landing_image/_img 1.png
  위클리_미션/landing_image/_img4 1.png
  위클리_미션/landing_image/akar-icons_facebook-fill.png
  위클리_미션/landing_image/akar-icons_twitter-fill.png
  위클리_미션/landing_image/akar-icons_youtube-fill.png
  위클리_미션/landing_image/ant-design_instagram-filled.png
  위클리_미션/landing_image/card 1-1.png
  위클리_미션/landing_image/card 3-1.png
  위클리_미션/landing_image/image 25.png
  위클리_미션/landing_image/image26.png
  위클리_미션/landing_image/img 4.png
  위클리_미션/landing_image/img3 1.png
  위클리_미션/landing_image/library.png
  위클리_미션/landing_image/logo.png
  위클리_미션/landing_image/스크린샷 2023-03-17 오후 3.22 1.png
  위클리_미션/landing_image/디스크립션 없는 팝업 1.png
  위클리_미션/landing_image/폴더 공유하기 팝업 1.png
  위클리_미션/privacy.html
  위클리_미션/signin.html
  위클리_미션/signin/eye-off.png
  위클리_미션/signin/eye-on.png
  위클리_미션/signin/google icon.png
  위클리_미션/signin/google.png
  위클리_미션/signin/kakao.png
  위클리_미션/signin/logo.png
  위클리_미션/signin/yellow.png
  위클리_미션/signup.html
  위클리_미션/style.css
  위클리_미션/style_signin.css
  위클리_미션/style_signup.css
Labels: 매운맛🔥

#79 [김민영]Week2 Week3
  codeit.code-workspace
  img/.DS_Store
  img/facebook.png
  img/instagram.png
  img/logo.jpg
  img/section1.png
  img/section2.png
  img/section3.png
  img/section4.png
  img/section5.png
  img/twitter.png
  img/youtube.png
  index.html
  signin/.DS_Store
  signin/icon/.DS_Store
  signin/icon/google.png
  signin/icon/google.svg
  signin/icon/googleicon.png
  signin/icon/kakao.png
  signin/icon/kakao.svg
  signin/icon/kakaoicon.png
  signin/icon/logo.png
  signin/index.html
  signin/style.css
  signup/.DS_Store
  signup/icon/.DS_Store
  signup/icon/google.svg
  signup/icon/googleicon.png
  signup/icon/kakao.svg
  signup/icon/kakaoicon.png
  signup/icon/logo.png
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛🔥, 미완성

#144 [김경주] Week3
  index.html
  preview.png
  public/img/_img.png
  public/img/_img1.png
  public/img/_img2.png
  public/img/_img3.png
  public/img/_img4.png
  public/img/eye-off.svg
  public/img/facebook.svg
  public/img/google.png
  public/img/instagram.svg
  public/img/kakao.svg
  public/img/logo.svg
  public/img/main.png
  public/img/preview.png
  public/img/twitter.svg
  public/img/youtube.svg
  signin.html
  signup.html
  src/color.css
  src/signin.css
  src/signup.css
  src/style.css
Labels: 미완성, 순한맛🐑 

#39 [김세동] Week3
  Assets/PreviewImage.png
  Assets/eye-off.svg
  Assets/eye-on.svg
  Assets/footer_X.png
  Assets/footer_facebook.png
  Assets/footer_instagram.png
  Assets/footer_youtube.png
  Assets/google.svg
  Assets/kakaoin.svg
  Assets/kakaoout.svg
  Assets/logo.svg
  Assets/main_Image.png
  Assets/main_image1.png
  Assets/main_image2.png
  Assets/main_image3.png
  Assets/main_image4.png
  Assets/social_kakaotalk.png
  Style.css
  index.html
  signIn.html
  signup.html
Labels: 매운맛🔥

#84 Part1 이진우 week3
  .gitignore
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
  src/viewMobile.css
  src/viewTablet.css
Labels: 매운맛🔥, 미완성

#56 [김혜중] week3
  css/color.css
  css/global.css
  css/index.css
  css/reset.css
  css/sign.css
  faq.html
  img/akar-icons_facebook-fill.svg
  img/akar-icons_twitter-fill.svg
  img/akar-icons_youtube-fill.svg
  img/ant-design_instagram-filled.svg
  img/cards.svg
  img/down.svg
  img/folder.svg
  img/login/eye-off.svg
  img/login/eye-on.svg
  img/login/google.svg
  img/login/kakao.svg
  img/login/logo.png
  img/logo.png
  img/main.svg
  img/meta-img.jpg
  img/search.svg
  img/share.svg
  index.html
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#127 [변지인] Week 3
  Linkbrary/faq.html
  Linkbrary/img/Card1.png
  Linkbrary/img/Card2.png
  Linkbrary/img/Card3.png
  Linkbrary/img/backmain-img.png
  Linkbrary/img/change.png
  Linkbrary/img/download.svg
  Linkbrary/img/eye-off.svg
  Linkbrary/img/eye-on.svg
  Linkbrary/img/google.png
  Linkbrary/img/icons_facebook-fill.svg
  Linkbrary/img/icons_instagram-filled.svg
  Linkbrary/img/icons_twitter-fill.svg
  Linkbrary/img/icons_youtube-fill.svg
  Linkbrary/img/kakao.png
  Linkbrary/img/logo.svg
  Linkbrary/img/main_img.png
  Linkbrary/img/search.png
  Linkbrary/img/share.png
  Linkbrary/img/total2.png
  Linkbrary/img/total4.png
  Linkbrary/index.html
  Linkbrary/index_style.css
  Linkbrary/privacy.html
  Linkbrary/signin.html
  Linkbrary/signin_style.css
  Linkbrary/signup.html
  Linkbrary/signup_style.css
Labels: 순한맛🐑 

#120 [김영은] Week 3
  .github/pull_request_template.md
  css/global.css
  css/pages/lending.css
  css/pages/sign.css
  css/reset.css
  css/style.css
  css/theme.css
  images/content01.png
  images/content02.png
  images/content03.png
  images/content04.png
  images/contents_dim.png
  images/googlelogo.png
  index.html
  signin.html
  signup.html
Labels: 미완성, 순한맛🐑 

#80 [길수진] week3
  faq.html
  img/akar-icons_facebook-fill.svg
  img/akar-icons_twitter-fill.svg
  img/akar-icons_youtube-fill.svg
  img/ant-design_instagram-filled.svg
  img/eye-off.svg
  img/eye-on.svg
  img/facebook.svg
  img/folder-name.png
  img/folder-share.png
  img/google.png
  img/google.svg
  img/hero.png
  img/image1.png
  img/image2.png
  img/image3.png
  img/image4.png
  img/kakao.svg
  img/logo.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/colors.css
  src/cta.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
Labels: 매운맛🔥

#119 [강경미] Week3
  images/99FE484C5C3451F218 1.svg
  images/Component 2.svg
  images/Component 3.svg
  images/_img-Mobile.png
  images/_img-Tablet.png
  images/_img.png
  images/_img1.png
  images/_img4.png
  images/google.png
  images/image 25.png
  images/image28.png
  images/img2.png
  images/img3.png
  images/sns/akar-icons_facebook-fill.png
  images/sns/akar-icons_twitter-fill.png
  images/sns/akar-icons_youtube-fill.png
  images/sns/ant-design_instagram-filled.png
  index.html
  signin.html
  signup.html
  stylesheets/main.css
  stylesheets/reset.css
  stylesheets/singnin.css
  stylesheets/singnup.css
  stylesheets/style.css
  stylesheets/style2.css
  stylesheets/theme.css
Labels: 순한맛🐑 

#122 Part1 김가은02 week03
  assets/footerIcons.png
  assets/hero-image.png
  assets/img1.png
  assets/img2.png
  assets/img3.png
  assets/img4.png
  assets/logo.png
  index.html
  signin/index.html
  signin/style.css
  style.css
  styles/common.css
  styles/reset.css
Labels: 미완성

#66 [김도현]
  assets/Linkbrary.png
  assets/cards/card1-1.png
  assets/cards/card1-2.png
  assets/cards/card1-3.png
  assets/cards/card1.png
  assets/cards/card2.png
  assets/cards/card3.png
  assets/cards/card4.png
  assets/cards/cards_img.png
  assets/icons/eye.png
  assets/icons/facebook.png
  assets/icons/google.png
  assets/icons/icon_box.png
  assets/icons/icon_box_y.png
  assets/icons/instagram.png
  assets/icons/kakao.png
  assets/icons/twitter.png
  assets/icons/youtube.png
  assets/login_btn.png
  assets/login_logo.png
  faq.html
  index.html
  privacy.html
  signin.html
  signup.html
  style/login.css
  style/style.css
Labels: 순한맛🐑 

#43 [박현우]Week3
  weekly-mission/css/basis.css
  weekly-mission/css/form.css
  weekly-mission/css/style.css
  weekly-mission/img/bgimg-3.png
  weekly-mission/img/google-logo.png
  weekly-mission/img/img1.png
  weekly-mission/img/img2.png
  weekly-mission/img/img3.png
  weekly-mission/img/img4.png
  weekly-mission/img/kakao.png
  weekly-mission/img/linkbrary.png
  weekly-mission/img/mainimg.png
  weekly-mission/index.html
  weekly-mission/signin.html
  weekly-mission/signup.html
Labels: 매운맛🔥

#15 [강진호] Week3
  css/common.css
  css/utility.css
  faq/index.html
  faq/style.css
  index.html
  privacy/index.html
  privacy/style.css
  public/akar-icons_facebook-fill.svg
  public/akar-icons_twitter-fill.svg
  public/akar-icons_youtube-fill.svg
  public/ant-design_instagram-filled.svg
  public/icon/Kakao.svg
  public/icon/download.svg
  public/icon/eye-off.svg
  public/icon/eye-on.svg
  public/icon/favorite.svg
  public/icon/google.svg
  public/icon/menu.svg
  public/landing-hero.png
  public/landing-section1.png
  public/landing-section2.png
  public/landing-section3.png
  public/landing-section4.png
  public/logo.svg
  public/metatag-twitter.png
  public/metatag.png
  signin/index.html
  signin/style.css
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛🔥

#123 [오도담] Week3
  README.md
  component/faq.html
  component/privacy.html
  component/signin.html
  component/signup.html
  image/Card-1.png
  image/Card-2.png
  image/Card-3.png
  image/Card-4.png
  image/Card-5.png
  image/Card-6.png
  image/Card-7.png
  image/Card-8.png
  image/Card-9.png
  image/Card.png
  image/folder/Card-1.png
  image/folder/Card-2.png
  image/folder/Card.png
  image/icons/akar-icons:facebook-fill.svg
  image/icons/akar-icons:twitter-fill.svg
  image/icons/akar-icons:youtube-fill.svg
  image/icons/ant-design:instagram-filled.svg
  image/icons/eye-off.svg
  image/icons/eye-on.svg
  image/icons/google-icon.svg
  image/icons/kakaotalk-bg.svg
  image/icons/kakaotalk-icon.svg
  image/landing/_img.png
  image/landing/_img1.png
  image/landing/_img4.png
  image/landing/img2.png
  image/landing/img3.png
  image/logo/logo.svg
  image/shared/Card-1.png
  image/shared/Card-2.png
  image/shared/Card-3.png
  image/shared/Card-4.png
  image/shared/Card-5.png
  image/shared/Card.png
  image/스크롤로 상단에 있는 링크 추가하기 가려지는 경우 화면/Card-1.png
  image/스크롤로 상단에 있는 링크 추가하기 가려지는 경우 화면/Card-2.png
  image/스크롤로 상단에 있는 링크 추가하기 가려지는 경우 화면/Card-3.png
  image/스크롤로 상단에 있는 링크 추가하기 가려지는 경우 화면/Card-4.png
  image/스크롤로 상단에 있는 링크 추가하기 가려지는 경우 화면/Card-5.png
  image/스크롤로 상단에 있는 링크 추가하기 가려지는 경우 화면/Card.png
  index.html
  styles/index.css
  styles/main.css
  styles/reset.css
  styles/signin-and-signup.css
  styles/style-constants.css
Labels: 매운맛🔥, 미완성

#21 [임동현] Week3
  .github/index.html
  .github/resource/css/index.css
  .github/resource/css/login.css
  .github/resource/font/Abel.ttf
  .github/resource/font/Acme/Acme.ttf
  .github/resource/font/pretendard/Pretendard-Black.ttf
  .github/resource/font/pretendard/Pretendard-Bold.ttf
  .github/resource/font/pretendard/Pretendard-ExtraBold.ttf
  .github/resource/font/pretendard/Pretendard-ExtraLight.ttf
  .github/resource/font/pretendard/Pretendard-Light.ttf
  .github/resource/font/pretendard/Pretendard-Medium.ttf
  .github/resource/font/pretendard/Pretendard-Regular.ttf
  .github/resource/font/pretendard/Pretendard-SemiBold.ttf
  .github/resource/font/pretendard/Pretendard-Thin.ttf
  .github/resource/image/eye-off.png
  .github/resource/image/facebook.png
  .github/resource/image/google.png
  .github/resource/image/instagram.png
  .github/resource/image/kakao.png
  .github/resource/image/logo.png
  .github/resource/image/logo_login.png
  .github/resource/image/sec1.png
  .github/resource/image/sec2.png
  .github/resource/image/sec3.png
  .github/resource/image/sec4.png
  .github/resource/image/sec5.png
  .github/resource/image/site_image.png
  .github/resource/image/twitter.png
  .github/resource/image/youtube.png
  .github/signIn.html
  .github/signUp.html
Labels: 매운맛🔥

#116 [이서인] Week3
  .DS_Store
  index.html
  signin.css
  signin.html
  signup.css
  signup.html
  source/.DS_Store
  source/1.png
  source/akar-icons_facebook-fill.svg
  source/akar-icons_twitter-fill.svg
  source/akar-icons_youtube-fill.svg
  source/ant-design_instagram-filled.svg
  source/chrome.svg
  source/kakao.svg
  source/landing/_img1.png
  source/landing/_img4.png
  source/landing/img2.png
  source/landing/img3.png
  source/logo.png
  style.css
Labels: 매운맛🔥

#69 [박지윤] Week3
  README.md
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  style/color.css
  style/global.css
  style/landing.css
  style/media.css
  style/reset.css
  style/sign.css
Labels: 순한맛🐑 

#53 [이재성] Week3
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
Labels: 매운맛🔥

#142 [최희문] Week3
  assets/Card1.png
  assets/Card2.png
  assets/Group 20.png
  assets/Linkbrary.png
  assets/card3.png
  assets/eye.png
  assets/facebook.png
  assets/folder.png
  assets/google.png
  assets/image 25.png
  assets/img.png
  assets/img2.png
  assets/instagram.png
  assets/kakao.png
  assets/logo.png
  assets/twitter.png
  assets/youtube.png
  faq.css
  faq.html
  index.css
  index.html
  privacy.css
  privacy.html
  signin.css
  signin.html
  signup.css
  signup.html
Labels: 매운맛🔥, 미완성

#147 [김가은99] week2
  faq.html
  image/_img 1.png
  image/_img4 1.png
  image/akar-icons_facebook-fill.svg
  image/akar-icons_twitter-fill.svg
  image/akar-icons_youtube-fill.svg
  image/ant-design_instagram-filled.svg
  image/image 25.png
  image/img 4.png
  image/img3 1.png
  image/logo.svg
  image/signin/99FE484C5C3451F218 1.svg
  image/signin/eye-on.svg
  image/signin/google.png
  image/signin/logo.svg
  index.html
  landing.css
  privacy.html
  signin.css
  signin.html
  signup.css
  signup.html
Labels: 매운맛🔥, 미완성

#25 [심민보]Week3
  html/faq.html
  html/privacy.html
  html/signin/index.html
  html/signup/index.html
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
Labels: 매운맛🔥

#48 [정기환] Week3
  README.md
  css/index.css
  css/sign.css
  faq.html
  images/eye.svg
  images/fbicon.svg
  images/googleicon.svg
  images/insticon.svg
  images/kakaoicon.svg
  images/landing-image-25.png
  images/landing1.png
  images/landing1point5.png
  images/landing2.png
  images/landing3.PNG
  images/landing4.png
  images/logo.svg
  images/meta_img.PNG
  images/twicon.svg
  images/yticon.svg
  index.html
  privacy.html
  sign_in.html
  sign_up.html
Labels: 매운맛🔥

#100 [이진호]Week3
  .gitignore
  faq.html
  icons/eyesoff.png
  icons/eyeson.png
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  imgs/contents1.png
  imgs/contents2.png
  imgs/contents3.png
  imgs/contents4.png
  imgs/goolge-logo.png
  imgs/main-img.png
  index.html
  privacy.html
  sign.css
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
  style.css
Labels: 매운맛🔥

#44 [이승훈] Week3
  .vscode/settings.json
  css/colors.css
  css/global.css
  css/reset.css
  css/signIn.css
  css/signUp.css
  css/style.css
  faq.html
  images/contents-01.png
  images/landing/akar-icons_facebook-fill.png
  images/landing/akar-icons_twitter-fill.png
  images/landing/akar-icons_youtube-fill.png
  images/landing/ant-design_instagram-filled.png
  images/landing/first-content.png
  images/landing/fourth-content.png
  images/landing/logo.png
  images/landing/main.png
  images/landing/second-content.png
  images/landing/third-content.png
  images/signIn/eye-off.svg
  images/signIn/google.png
  images/signIn/icon_google.svg
  images/signIn/icon_kakao.svg
  images/signIn/icon_kakao2.svg
  images/signIn/logo.svg
  index.html
  privacy.html
  signIn.html
  signUp.html
Labels: 매운맛🔥

#20 [김시현] week3
  .DS_Store
  css/global.css
  css/landing.css
  css/sign.css
  docs/README.md
  faq.html
  index.html
  privacy.html
  public/.DS_Store
  public/images/google-logo.png
  public/images/kakao-logo.svg
  public/images/landing-akar-icons-facebook-fill.png
  public/images/landing-akar-icons-twitter-fill.png
  public/images/landing-akar-icons-youtube-fill.png
  public/images/landing-ant-design-instagram-filled.png
  public/images/landing-image-25.png
  public/images/landing-logo.png
  public/images/landing-s2.png
  public/images/landing-s3.png
  public/images/landing-s4.png
  public/images/landing-s5.png
  public/images/meta-tag.jpg
  signin.html
  signup.html
Labels: 매운맛🔥

#104 [정봉찬] Week3
  .gitignore
  css/common.css
  css/global.css
  css/main.css
  css/reset.css
  css/sign.css
  css/signin.css
  css/signup.css
  faq/index.html
  images/logo.svg
  images/main/facebook_icon.png
  images/main/instagram_icon.png
  images/main/intro_folder.png
  images/main/intro_main.png
  images/main/intro_save.png
  images/main/intro_search.png
  images/main/intro_share.png
  images/main/twitter_icon.png
  images/main/youtube_icon.png
  images/sign/eye_off.svg
  images/sign/eye_on.svg
  images/sign/google_icon.png
  images/sign/kakao_icon.png
  index.html
  privacy/index.html
  signin/index.html
  signup/index.html
Labels: 매운맛🔥, 미완성

#49 [조한빈] Week3
  images/logo.png
  images/logo.svg
  images/main1.png
  images/main2-0.png
  images/main2-1.png
  images/main2-2.png
  images/main2-3.png
  images/main3.png
  images/main4.png
  images/main5.png
  images/ogimage.jpg
  images/signin/google.png
  images/signin/kakao.svg
  images/sns/facebook.png
  images/sns/instagram.png
  images/sns/twitter.png
  images/sns/youtube.png
  index.html
  signin/index.html
  signin/style.css
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛🔥

#52 [이유진] Week3
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.css
  index.html
  signin/signin.css
  signin/signin.html
  signup/signup.css
  signup/signup.html
Labels: 매운맛🔥

#114 [이유승] Week3
  .vscode/settings.json
  assets/image/Google.png
  assets/image/Kakaotalk.png
  assets/image/contents-1.png
  assets/image/contents-2.png
  assets/image/contents-3.png
  assets/image/contents-4.png
  assets/image/eye-on.png
  assets/image/facebook.png
  assets/image/header.png
  assets/image/instagram.png
  assets/image/logo.png
  assets/image/twitter.png
  assets/image/youtube.png
  index.html
  signin/index.html
  signin/style.css
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛🔥

#62 [이지연]Week3
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  images/_img1.png
  images/_img4.png
  images/facebook.png
  images/google.png
  images/image25.png
  images/img2.png
  images/img3.png
  images/instagram.png
  images/kakaotalk.png
  images/logo.png
  images/twitter.png
  images/youtube.png
  index.html
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#78 [임채민]Week3
  faq.html
  images/facebook.svg
  images/google.png
  images/image 25.png
  images/img1.png
  images/img2.png
  images/img3.png
  images/img4.png
  images/instagram.svg
  images/kakao.svg
  images/kakao_bg.svg
  images/library-og.jpg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  styles/signin.css
  styles/style.css
Labels: 매운맛🔥

#88 [류지영] Week3
  .gitignore
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  images/수박망곰.jpeg
  index.html
  privacy.html
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
  코드잇.code-workspace
Labels: 매운맛🔥

#121 [김진아] Week 3
  week2/faq.html
  week2/images/eye-off.svg
  week2/images/facebook.svg
  week2/images/google.png
  week2/images/hero.png
  week2/images/image1.png
  week2/images/image2.png
  week2/images/image3.png
  week2/images/image4.png
  week2/images/instagram.svg
  week2/images/kakao.svg
  week2/images/logo.svg
  week2/images/twitter.svg
  week2/images/youtube.svg
  week2/index.html
  week2/privacy.html
  week2/signin.html
  week2/signup.html
  week2/src/colors.css
  week2/src/global.css
  week2/src/index.css
  week2/src/reset.css
  week2/src/sign.css
  week3/faq.html
  week3/images/eye-off.svg
  week3/images/facebook.svg
  week3/images/google.png
  week3/images/hero.png
  week3/images/image1.png
  week3/images/image2.png
  week3/images/image3.png
  week3/images/image4.png
  week3/images/instagram.svg
  week3/images/kakao.svg
  week3/images/logo.svg
  week3/images/twitter.svg
  week3/images/youtube.svg
  week3/index.html
  week3/privacy.html
  week3/signin.html
  week3/signup.html
  week3/src/colors.css
  week3/src/global.css
  week3/src/index.css
  week3/src/reset.css
  week3/src/sign.css
Labels: 매운맛🔥, 미완성

#136 [권민서] Week3
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
Labels: 매운맛🔥

#54 [한진희]Week3
  css/linkbrary_Landing.css
  css/linkbrary_signin.css
  css/linkbrary_signup.css
  html/Linkbrary(faq).html
  html/Linkbrary(privacy).html
  html/Linkbrary(signin).html
  html/Linkbrary(signup).html
  html/index.html
  image/akar-icons_facebook-fill.png
  image/akar-icons_twitter-fill.png
  image/akar-icons_youtube-fill.png
  image/ant-design_instagram-filled.png
  image/eye-on.png
  image/google.png
  image/googlecucle.png
  image/kakao.png
  image/kakaocucle.png
  image/logo.png
  image/mainimg.PNG
  image/mainimg1.png
  image/mainimg2.png
  image/mainimg3.png
  image/mainimg4.png
  image/sns메인이미지.png
Labels: 매운맛🔥

#110 [홍성욱] Week3
  .vscode/settings.json
  faq.html
  images/contents-01-img.png
  images/contents-02-img.png
  images/contents-03-img.png
  images/contents-04-img.png
  images/contents-05-img.png
  images/eye-off.png
  images/facebook.png
  images/google.png
  images/instagram.png
  images/kakao.png
  images/logo.png
  images/twitter.png
  images/youtube.png
  index.html
  signin.html
  signup.html
  src/colors.css
  src/sign.css
  src/style.css
Labels: 매운맛🔥

#103 [박기범]Week3
  css/signin.css
  css/signup.css
  css/style.css
  images/card.png
  images/card1.png
  images/card2.png
  images/card3.png
  images/eye-off.svg
  images/facebook_circle.svg
  images/facebook_icon.svg
  images/google.png
  images/google_circle.svg
  images/group 20.svg
  images/img1.png
  images/img2.png
  images/img3.png
  images/img4.png
  images/img5.png
  images/instagram_icon.svg
  images/kakao.svg
  images/library.PNG
  images/logo.svg
  images/twitter_icon.svg
  images/youtube_icon.svg
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥, 미완성

#1 [김민정] Week3
  assets/Linkbrary.png
  assets/cards/card1-1.png
  assets/cards/card1-2.png
  assets/cards/card1-3.png
  assets/cards/card1.png
  assets/cards/card2.png
  assets/cards/card3.png
  assets/cards/card4.png
  assets/cards/cards_img.png
  assets/icons/eye-off.png
  assets/icons/icon_box.png
  assets/icons/icon_box_y.png
  assets/icons/icon_facebook.png
  assets/icons/icon_google.png
  assets/icons/icon_instagram.png
  assets/icons/icon_kakao.png
  assets/icons/icon_twitter.png
  assets/icons/icon_youtube.png
  assets/login_btn.png
  assets/login_logo.png
  faq.html
  index.html
  privacy.html
  signin.html
  signup.html
  style/login.css
  style/style.css
Labels: 매운맛🔥

#67 최원석[Week3]
  LandingPage.html
  SignIn.html
  SignUp.html
  css/Sign.css
  css/global.css
  css/style.css
  icons/Card-1.png
  icons/Card-2.png
  icons/Card.png
  icons/Group 20.png
  icons/_img1.png
  icons/_img4.png
  icons/akar-icons_facebook-fill.png
  icons/akar-icons_twitter-fill.png
  icons/akar-icons_youtube-fill.png
  icons/ant-design_instagram-filled.png
  icons/eye-off.svg
  icons/google.png
  icons/image 25 (2).png
  icons/image 25.png
  icons/image2.png
  icons/image3.png
  icons/kakao.svg
  icons/logo.png
  icons/logo_sign.png
  icons/폴더 공유하기 팝업 1.png
Labels: 매운맛🔥

#63 [안연아]Week3
  faq.html
  images/card1.png
  images/card2.png
  images/card3.png
  images/card4.png
  images/download.svg
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/head-image.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/view.png
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/colors.css
  src/landing.css
  src/set.css
  src/sign.css
Labels: 매운맛🔥

#81 [구승모] week3
  assets/icons/akar-icons-facebook-fill.svg
  assets/icons/akar-icons-twitter-fill.svg
  assets/icons/akar-icons-youtube-fill.svg
  assets/icons/ant-design-instagram-filled.svg
  assets/icons/eye-off.svg
  assets/icons/eye-on.svg
  assets/icons/googleicon.svg
  assets/icons/kakaoicon.svg
  assets/icons/logo.svg
  assets/images/section1-img.png
  assets/images/section2-img.png
  assets/images/section3-img.png
  assets/images/section4-img.png
  assets/images/section5-img.png
  css/landing.css
  css/signin.css
  css/signup.css
  css/style.css
  faq.html
  index.html
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#152 [유승재] Week2
  .DS_Store
  image/add-link.png
  image/change-name.png
  image/eye-off.png
  image/icon-facebook.png
  image/icon-google.svg
  image/icon-instagram.png
  image/icon-kakaotalk.svg
  image/icon-twitter.png
  image/icon-youtube.png
  image/logo.png
  image/save-link.png
  image/search.png
  image/share.png
  index.html
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#112 [류광현]week2
  _redirects
  home.css
  index.html
  landing/Card 1.png
  landing/Card-1.png
  landing/Card.png
  landing/Group 20.svg
  landing/akar-icons_facebook-fill.svg
  landing/akar-icons_twitter-fill.svg
  landing/akar-icons_youtube-fill.svg
  landing/ant-design_instagram-filled.svg
  landing/codeit-serch.png
  landing/eye-on.svg
  landing/folder-name-img.png
  landing/folder-share.png
  landing/google-back.svg
  landing/google.png
  landing/image 25.png
  landing/image-28.png
  landing/image1.png
  landing/kakaotalk-back.svg
  landing/kakaotalk.svg
  landing/logo.svg
  login.html
  login.js
  pull_request_template.md
  sign-up.html
  workflows/delete-merged-branch-config.yml
Labels: 미완성, 순한맛🐑 

#159 [김태은]Week2
  images/99FE484C5C3451F218 1.png
  images/akar-icons_facebook-fill.png
  images/akar-icons_twitter-fill.png
  images/akar-icons_youtube-fill.png
  images/ant-design_instagram-filled.png
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/logo.png
  images/logo1.png
  index.html
  signin.html
  signup.html
  src/landing.css
  src/signup.css
Labels: 매운맛🔥, 미완성

#137 [김정건] week3
  .vscode/settings.json
  icon/CTA.jpg
  icon/CTA2.jpg
  icon/Component 2.png
  icon/Component 3.png
  icon/Group 20.svg
  icon/contents-01-image.png
  icon/eye-off.svg
  icon/eye-on.svg
  icon/facebooklogo.svg
  icon/instgram_logo.svg
  icon/logo.jpg
  icon/logo.svg
  icon/state.png
  icon/twitter_logo.svg
  icon/youtube_logo.svg
  images/_img.png
  images/_img1.png
  images/_img2.png
  images/_img3.png
  images/_img4.png
  index.html
  signin.html
  signup.html
  styles.css
  test.js
Labels: 미완성, 순한맛🐑 

#111 [이동현] Week3
  .DS_Store
  .prettierrc
  .vscode/settings.json
  assets/.DS_Store
  assets/css/auth-form.css
  assets/css/common/footer.css
  assets/css/common/header.css
  assets/css/common/reset.css
  assets/css/main.css
  assets/fonts/Pretendard-Bold.woff2
  assets/fonts/Pretendard-Medium.woff2
  assets/fonts/Pretendard-Regular.woff2
  assets/fonts/Pretendard-SemiBold.woff2
  assets/images/icon/facebook-icon.svg
  assets/images/icon/google-login.svg
  assets/images/icon/instagram-icon.svg
  assets/images/icon/kakao-login.svg
  assets/images/icon/password-eye-icon.svg
  assets/images/icon/twitter-icon.svg
  assets/images/icon/youtube-icon.svg
  assets/images/linkbrary.jpg
  assets/images/logo.svg
  assets/images/manual-management.png
  assets/images/manual-save.png
  assets/images/manual-search.png
  assets/images/manual-share.png
  assets/images/visual.png
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥

#85 [홍재훈]Week3
  linkbrary/css/common.css
  linkbrary/css/main.css
  linkbrary/css/responsive/mobile.css
  linkbrary/css/responsive/tablet.css
  linkbrary/css/signin.css
  linkbrary/css/signup.css
  linkbrary/image/google_icon.png
  linkbrary/image/kakao_icon.png
  linkbrary/image/sub1_img.png
  linkbrary/image/sub2_img.png
  linkbrary/image/sub3_img.png
  linkbrary/image/sub4_img.png
  linkbrary/image/title_img.png
  linkbrary/index.html
  linkbrary/pages/faq.html
  linkbrary/pages/privacy.html
  linkbrary/pages/signin.html
  linkbrary/pages/signup.html
Labels: 매운맛🔥

#59 [윤병현] week3
  css/index.css
  css/sign.css
  css/signup.css
  icon/Component 2.png
  icon/Component 3.png
  icon/Group 20.svg
  icon/eye-off.svg
  icon/eye-on.svg
  icon/facebooklogo.svg
  icon/instgram_logo.svg
  icon/logo.svg
  icon/twitter_logo.svg
  icon/youtube_logo.svg
  images/_img.png
  images/_img1.png
  images/_img2.png
  images/_img3.png
  images/_img4.png
  index.html
  sign.html
  signup.html
Labels: 매운맛🔥

#61 [김수환]Week3
  .vscode/settings.json
  css/style.css
  css/style_signin.css
  css/style_signup.css
  faq.html
  img/png/contents-01-image.png
  img/png/contents-02-image.png
  img/png/contents-03-image.png
  img/png/contents-04-image.png
  img/png/contents-05-image.png
  img/png/google-logo.png
  img/png/library.png
  img/svg/eye-off.svg
  img/svg/eye-on.svg
  img/svg/facebook-logo.svg
  img/svg/instafram-logo.svg
  img/svg/kakao-background.svg
  img/svg/kakao-logo.svg
  img/svg/logo-sign.svg
  img/svg/logo.svg
  img/svg/twitter-logo.svg
  img/svg/youtube-logo.svg
  index.html
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#68 [박준영]Week3
  .gitignore
  .stylelintrc.json
  assets/icons/eye-off.svg
  assets/icons/facebook-logo.svg
  assets/icons/google-logo.svg
  assets/icons/instagram-logo.svg
  assets/icons/kakao-logo.svg
  assets/icons/linkbrary-logo.svg
  assets/icons/twitter-logo.svg
  assets/icons/youtube-logo.svg
  assets/landing-download.svg
  assets/landing-folder.svg
  assets/landing-main.svg
  assets/landing-search.svg
  assets/landing-share.svg
  assets/푸바오.jpeg
  css/global.css
  css/index.css
  css/sign.css
  index.html
  package-lock.json
  pages/faq.html
  pages/privacy.html
  pages/signin.html
  pages/signup.html
  yarn.lock
Labels: 매운맛🔥

#22 [김준영] Week3
  src/css/index.css
  src/css/login.css
  src/css/style.css
  src/faq.html
  src/index.html
  src/privacy.html
  src/resource/Linkbrary_large_logo.png
  src/resource/Linkbrary_small_logo.png
  src/resource/facebook_logo.png
  src/resource/google_logo.png
  src/resource/instagram_logo.png
  src/resource/kakao_logo.png
  src/resource/landing_img1.png
  src/resource/landing_img2.png
  src/resource/landing_img3.png
  src/resource/landing_img4.png
  src/resource/main_banner_img.png
  src/resource/twitter_logo.png
  src/resource/view_password_icon.png
  src/resource/youtube_logo.png
  src/signin.html
  src/signup.html
Labels: 매운맛🔥

#102 [김예진] Week3
  images/eye.svg
  images/facebook.svg
  images/google.png
  images/header-img.png
  images/img2.png
  images/img3.png
  images/img4.png
  images/img5.png
  images/instagram.svg
  images/kakao.png
  images/logo.svg
  images/maltese.jpg
  images/section1.png
  images/sns.png
  images/twitter.svg
  images/youtube.svg
  index.html
  signin.html
  signup.html
  src/colors.css
  src/index.css
  src/index_px.css
  src/sign.css
Labels: 매운맛🔥

#107 [김창민]week3
  .DS_Store
  landing-2/.DS_Store
  landing-2/.gitignore
  landing-2/faq.html
  landing-2/images/eye-off.svg
  landing-2/images/facebook.svg
  landing-2/images/google.png
  landing-2/images/hero.png
  landing-2/images/image1.png
  landing-2/images/image2.png
  landing-2/images/image3.png
  landing-2/images/image4.png
  landing-2/images/instagram.svg
  landing-2/images/kakao.svg
  landing-2/images/logo.svg
  landing-2/images/twitter.svg
  landing-2/images/youtube.svg
  landing-2/index.html
  landing-2/privacy.html
  landing-2/signin.html
  landing-2/signup.html
  landing-2/src/colors.css
  landing-2/src/global.css
  landing-2/src/landing.css
  landing-2/src/reset.css
  landing-2/src/rwd.css
  landing-2/src/sign.css
Labels: 매운맛🔥, 미완성

#42 [김규헌]Week3
  css/color.css
  css/landing.css
  css/signin.css
  css/signup.css
  image/eye-off.svg
  image/eye-on.svg
  image/facebook.svg
  image/google.png
  image/header.png
  image/instagram.svg
  image/kakao.png
  image/logo.svg
  image/meta-image.png
  image/section1.png
  image/section2.png
  image/section3.png
  image/section4.png
  image/twitter.svg
  image/youtube.svg
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥

#129 [박소현] Week3
  .gitignore
  assets/icon/eye-off.svg
  assets/icon/eye-on.svg
  assets/icon/facebook.svg
  assets/icon/google.svg
  assets/icon/instagram.svg
  assets/icon/kakao.svg
  assets/icon/twitter.svg
  assets/icon/youtube.svg
  assets/image/logo.svg
  assets/image/main.png
  assets/image/manage-link.png
  assets/image/save-link.png
  assets/image/search-link.png
  assets/image/share-link.png
  index.html
  pages/faq.html
  pages/privacy.html
  pages/signin.html
  pages/signup.html
  src/styles/color.css
  src/styles/global.css
  src/styles/main.css
  src/styles/sign.css
Labels: 매운맛🔥

#133 [신가은]Week3
  .gitignore
  .vscode/settings.json
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
Labels: 미완성, 순한맛🐑 

#130 [백승아] week3
  assets/icon/Linkbrary.svg
  assets/icon/eye-off.svg
  assets/icon/facebook.svg
  assets/icon/google .svg
  assets/icon/instagram.svg
  assets/icon/kakao.svg
  assets/icon/twitter.svg
  assets/icon/youtube.svg
  assets/images/main.png
  assets/images/management.png
  assets/images/save.png
  assets/images/search.png
  assets/images/share.png
  faq.html
  index.html
  privacy.html
  signin.html
  signup.html
  style/colors.css
  style/global.css
  style/reset.css
  style/sign.css
  style/style.css
Labels: 매운맛🔥, 순한맛🐑 

#109 [한태욱] week3
  .gitignore
  assets/image/hero.png
  assets/image/main_folder.png
  assets/image/main_search.png
  assets/image/main_share.png
  assets/image/main_store.png
  assets/logo/eye-off.svg
  assets/logo/facebook.svg
  assets/logo/google.png
  assets/logo/instagram.svg
  assets/logo/kakao.svg
  assets/logo/logo.svg
  assets/logo/twitter.svg
  assets/logo/youtube.svg
  css/colors.css
  css/global.css
  css/landing.css
  css/reset.css
  css/sign.css
  faq.html
  index.html
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#47 [강영훈] Week3
  css/color.css
  css/global.css
  css/landing.css
  css/reset.css
  css/sign.css
  html/faq.html
  html/privacy.html
  html/signin.html
  html/signup.html
  image/icon/eye.svg
  image/logo/Linkbrary.svg
  image/logo/facebook.svg
  image/logo/google.svg
  image/logo/instagram.svg
  image/logo/kakao.svg
  image/logo/twitter.svg
  image/logo/youtube.svg
  image/screen/main.svg
  image/screen/manage.svg
  image/screen/save-link.svg
  image/screen/search.svg
  image/screen/share.svg
  image/thumbnail/books_1920.jpg
  index.html
Labels: 순한맛🐑 

#34 [이도원] week3
  images/Vector.png
  images/_img.png
  images/_img1.png
  images/_img4.png
  images/eye-off.svg
  images/facebook_icon.svg
  images/google.png
  images/img2.png
  images/img3.png
  images/instagram-icon.svg
  images/kakao.svg
  images/logo.svg
  images/meta.png
  images/twitter_icon.svg
  images/youtube_icon.svg
  index.html
  signin.html
  singup.html
  style.css
Labels: 매운맛🔥

#106 [최민준] week3
  css/login.css
  css/reset.css
  css/root.css
  css/style.css
  faq.html
  img/Card 1.png
  img/Card-1.png
  img/Card.png
  img/Group 20.svg
  img/akar-icons_facebook-fill.svg
  img/akar-icons_twitter-fill.svg
  img/akar-icons_youtube-fill.svg
  img/ant-design_instagram-filled.svg
  img/bookmark.png
  img/card-img.png
  img/google-logo.png
  img/image 25.png
  img/logo.svg
  img/search-link.png
  img/share.png
  index.html
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#138 [이우혁] Week4
  css/index.css
  css/signin.css
  css/signup.css
  index.html
  js/pw-input-type.js
  js/regExp.js
  js/signin.js
  js/signup.js
  js/user-info.js
  js/vaild.js
  signin.html
  signup.html
Labels: 매운맛🔥

#118 [손승현] Week 2 and 3
  img/eye-off.png
  img/eye-on.png
  img/facebook.png
  img/googleicon.png
  img/img1.png
  img/img2.png
  img/img3.png
  img/img4.png
  img/instagram.png
  img/kakaoicon.png
  img/logo.png
  img/mainimg.png
  img/mainimg2.png
  img/twitter.png
  img/youtube.png
  index.html
  palette.css
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#146 [이주형] Week3
  .vscode/launch.json
  CTA.png
  CTA1.png
  Component 2.png
  Component 3.png
  Facebook.svg
  Kakao.svg
  _close.svg
  akar-icons_facebook-fill.svg
  akar-icons_twitter-fill.svg
  akar-icons_youtube-fill.svg
  ant-design_instagram-filled.svg
  colors.css
  eye-off.png
  global.css
  hero.png
  image1.png
  image2.png
  image3.png
  image4.png
  index.html
  link.svg
  logo.png
  main.css
  reset.css
  sign.css
  signin.html
  signup.html
  star.svg
Labels: 매운맛🔥, 미완성

#163 [김재영]Week4
  folder.html
  index.html
  sign.css
  signin.html
  signin.js
  signup.html
  style.css
Labels: 매운맛🔥

#35 [김수정] week3
  image/eye-off.svg
  image/facebook.svg
  image/google.png
  image/hero.png
  image/image1.png
  image/image2.png
  image/image3.png
  image/image4.png
  image/instagram.svg
  image/kakao.svg
  image/logo.svg
  image/twitter.svg
  image/youtube.svg
  index.html
  signin.html
  signup.html
  style/colors.css
  style/global.css
  style/landing.css
  style/reset.css
  style/sign.css
  style/style.css
Labels: 매운맛🔥

#148 [차수지] Week4
  assets/sign/eye-off.svg
  assets/sign/eye-on.svg
  css/sign.css
  folder.html
  js/sign.js
  signin.html
Labels: 매운맛🔥

#198 [강나리] Week4
  images/eye-on.svg
  index.html
  js/index.js
  js/signin.js
  signin.html
  signup.html
  styles/signin.css
  styles/signup.css
  styles/style.css
Labels: 순한맛🐑 

#217 [권나은] Week4
  index.html
  inputform_change.js
  loginin.css
  loginin.html
  mainpage.css
  signup.css
  signup.html
Labels: 매운맛🔥

#231 [윤여진] week4
  css/color.css
  css/main.css
  css/media.css
  css/signin.css
  css/signup.css
  folder.html
  images/icon-close-eye.png
  images/icon-open-eye.png
  index.html
  js/signin.js
  js/signup.js
  signin.html
  signup.html
Labels: 매운맛🔥

#234 [김보경]week4
  README.md
  img/google.png
  img/kakao.png
  index.html
  signin/index.html
  signin/signin.css
  signin/signin.html
  signin/signin.js
  signup/google.png
  signup/index.html
  signup/kakao.png
  signup/signup.css
  signup/signup.html
  style.css
  svg/facebook.svg
  svg/instagram.svg
  svg/logo-signin.svg
  svg/logo.svg
  svg/twitter.svg
  svg/youtube.svg
Labels: 매운맛🔥, 미완성

#226 [박우혁]week4
  .gitignore
  faq.html
  images/eye-off.svg
  images/eye-on.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/index.css
  src/landing.css
  src/reset.css
  src/sign.css
  src/sign.js
Labels: 순한맛🐑 

#191 [김재성] week4
  css/config.css
  css/index.css
  css/reset.css
  css/sign.css
  folder/index.html
  folder/js/folder.js
  index.html
  js/common.js
  signin/css/signin.css
  signin/index.html
  signin/js/signin.js
  signup/index.html
  signup/js/signup.js
Labels: 매운맛🔥

#166 [김수환] Week4
  css/style_signin.css
  folder.html
  js/signin.js
  signin.html
Labels: 매운맛🔥

#205 [황경수] week4
  CSS/sign/sign.css
  CSS/style.css
  assets/svg/eye-off.svg
  assets/svg/eye-on.svg
  folder/index.html
  index.html
  script/signin.js
  signin/index.html
  signup/index.html
Labels: 매운맛🔥

#212 [소남주] Week4
  images/eye-off.png
  images/eye-on.png
  images/og_image.png
  index.html
  login/index.html
  login/index.js
  login/login_style.css
  signup/index.html
  signup/index.js
  style.css
Labels: 매운맛🔥

#250 Part1 오도담 week4
  component/folder.html
  component/signin.html
  component/signup.html
  image/Card-1.png
  image/Card-2.png
  image/Card-3.png
  image/Card-4.png
  image/Card-5.png
  image/Card-6.png
  image/Card-7.png
  image/Card-8.png
  image/Card-9.png
  image/Card.png
  image/folder/Card-1.png
  image/folder/Card-2.png
  image/folder/Card.png
  image/landing/img0.png
  image/landing/img1.png
  image/landing/img4.png
  image/shared/Card-1.png
  image/shared/Card-2.png
  image/shared/Card-3.png
  image/shared/Card-4.png
  image/shared/Card-5.png
  image/shared/Card.png
  image/스크롤로 상단에 있는 링크 추가하기 가려지는 경우 화면/Card-1.png
  image/스크롤로 상단에 있는 링크 추가하기 가려지는 경우 화면/Card-2.png
  image/스크롤로 상단에 있는 링크 추가하기 가려지는 경우 화면/Card-3.png
  image/스크롤로 상단에 있는 링크 추가하기 가려지는 경우 화면/Card-4.png
  image/스크롤로 상단에 있는 링크 추가하기 가려지는 경우 화면/Card-5.png
  image/스크롤로 상단에 있는 링크 추가하기 가려지는 경우 화면/Card.png
  index.html
  scripts/signin.js
  styles/base.css
  styles/landing.css
  styles/main.css
  styles/signin-and-signup.css
  styles/style-constants.css
Labels: 매운맛🔥, 미완성

#173 [문지혜] Week4
  folder.html
  index.html
  index.js
  public/images/landing/main-image.png
  public/images/landing/section1.png
  public/images/landing/section2.png
  public/images/landing/section3.png
  public/images/landing/section4.png
  public/images/sign/eye-off.png
  public/images/sign/eye-on.png
  public/images/sign/logo.png
  sign.css
  sign.js
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#239 [양서연] Week4
  css/landing.css
  css/palette.css
  css/signin.css
  css/signup.css
  folder.html
  images/99FE484C5C3451F218 1.svg
  images/Linkbrary-logo.svg
  images/icon-facebook.svg
  images/icon-google.png
  images/icon-instagram.svg
  images/icon-kakao.png
  images/icon-twitter.svg
  images/icon-youtube.svg
  images/img1.png
  images/img4.png
  index.html
  json/signin.js
  signin.html
  signup.html
Labels: 매운맛🔥

#259 [최민혁]week4
  faq/index.html
  folder/index.html
  image/Linkbrary.png
  image/_img.png
  image/_img1.png
  image/_img4.png
  image/facebook.png
  image/img2.png
  image/img3.png
  image/instargram.png
  image/twitter.png
  image/youtube.png
  index.html
  main.css
  main.js
  palette.css
  privacy/index.html
  signin/signin.css
  signin/signin.html
  signin/signin.js
  signin/signin_image/eye-off.png
  signin/signin_image/google.png
  signin/signin_image/kakao.png
  signup/signup.css
  signup/signup.html
  signup/signup_image/eye-off.png
  signup/signup_image/google.png
  signup/signup_image/kakao.png
Labels: 미완성

#229 [김동현] Week4
  folder.html
  images/sign_logo.svg
  index.html
  signin.html
  signup.html
  src/css/global.css
  src/css/landing.css
  src/css/reset.css
  src/css/sign.css
  src/images/eye-off.svg
  src/images/eye-on.svg
  src/images/icon_facebook.svg
  src/images/icon_google.png
  src/images/icon_instagram.svg
  src/images/icon_kakao.png
  src/images/icon_twitter.svg
  src/images/icon_youtube.svg
  src/images/img1.png
  src/images/img2.png
  src/images/img3.png
  src/images/img4.png
  src/images/img_main.png
  src/images/logo.svg
  src/images/preview_library.png
  src/script/sign.js
Labels: 매운맛🔥

#238 [임동현] Week4
  .github/resource/css/login.css
  .github/resource/image/eye-on.png
  .github/resource/js/login.js
  .github/signIn.html
Labels: 매운맛🔥

#256 [이유승] Week4
  .vscode/settings.json
  folder.html
  signin/index.html
  signin/index.js
Labels: 매운맛🔥, 미완성

#251 [변지인] Week 4
  Linkbrary/index.html
  Linkbrary/index_style.css
  Linkbrary/signin.html
  Linkbrary/signup.html
  css/common.css
  css/index.css
  css/reset.css
  css/signin.css
  css/signup.css
  javascript/validation.js
  구조 스케치/index.png
Labels: 미완성, 순한맛🐑 

#179 [유아름] Week4
  folder/index.html
  images/og_image.png
  index.html
  login.js
  signin/index.html
  signup/index.html
  style.css
  styles/common.css
  styles/fonts/icomoon.eot
  styles/fonts/icomoon.svg
  styles/fonts/icomoon.ttf
  styles/fonts/icomoon.woff
  styles/login-page.css
Labels: 매운맛🔥

#257 [김경주] Week 4
  folder.html
  index.html
  js/signin.js
  public/img/eye-on.svg
  signin.html
  signup.html
  src/signin.css
  src/signup.css
  src/style.css
Labels: 매운맛🔥, 순한맛🐑 

#169 [김효진] week4
  folder.html
  images/banner.png
  images/eye-on.svg
  images/feature-1.png
  images/feature-2.png
  images/feature-3.png
  images/feature-4.png
  index.html
  js/sign.js
  signin.html
  src/landing.css
  src/sign.css
Labels: 순한맛🐑 

#162 [기송은] Week4
  common.css
  faq/index.html
  faq/style.css
  folder/index.html
  folder/style.css
  hompage.css
  hompage1.css
  index.html
  privacy/index.html
  privacy/style.css
  public/images/landing_image/Card-1.png
  public/images/landing_image/Card.png
  public/images/landing_image/Group-20.png
  public/images/landing_image/_img-1.png
  public/images/landing_image/_img4-1.png
  public/images/landing_image/akar-icons_facebook-fill.png
  public/images/landing_image/akar-icons_twitter-fill.png
  public/images/landing_image/akar-icons_youtube-fill.png
  public/images/landing_image/ant-design_instagram-filled.png
  public/images/landing_image/card-1-1.png
  public/images/landing_image/card-3-1.png
  public/images/landing_image/image-25.png
  public/images/landing_image/image26.png
  public/images/landing_image/img-4.png
  public/images/landing_image/img3-1.png
  public/images/landing_image/library.png
  public/images/landing_image/logo.png
  public/images/signin-image/eye-off.png
  public/images/signin-image/eye-on.png
  public/images/signin-image/google-icon.png
  public/images/signin-image/google.png
  public/images/signin-image/kakao.png
  public/images/signin-image/logo.png
  public/images/signin-image/yellow.png
  signin/index.html
  signin/index.js
  signin/index1.js
  signin/style.css
  signin/style1.css
  signup/index.html
  signup/style.css
  signup/style1.css
  위클리_미션/index.html
  위클리_미션/landing_image/Card 1.png
  위클리_미션/landing_image/스크린샷 2023-03-17 오후 3.22 1.png
  위클리_미션/landing_image/디스크립션 없는 팝업 1.png
  위클리_미션/landing_image/폴더 공유하기 팝업 1.png
  위클리_미션/signin.html
  위클리_미션/signup.html
Labels: 매운맛🔥

#242 Part1 김현찬 week4
  faq/index.html
  images/Group 20.svg
  images/_dim.svg
  images/facebook.svg
  images/header-image.svg
  images/image 25.svg
  images/instagram.svg
  images/section-image1.svg
  images/section-image2.svg
  images/section-image3.svg
  images/section-image4.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy/index.html
  signin/images/google.svg
  signin/images/kakao.svg
  signin/index.html
  signin/index.js
  signin/style.css
  signup/images/google.svg
  signup/images/kakao.svg
  signup/images/logo.svg
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛🔥, 미완성

#192 [심민보] Week4
  html/faq.html
  html/folder.html
  html/privacy.html
  html/signin/index.html
  html/signup/index.html
  images/eye-on.png
  index.html
  js/signin.js
  src/landing.css
  src/sign.css
Labels: 매운맛🔥

#176 [진찬용] week4
  asset/img/landing/Linkbrary.png
  asset/img/landing/_img.png
  asset/img/landing/_img1.png
  asset/img/landing/_img4.png
  asset/img/landing/akar-icons_facebook-fill.png
  asset/img/landing/akar-icons_twitter-fill.png
  asset/img/landing/akar-icons_youtube-fill.png
  asset/img/landing/ant-design_instagram-filled.png
  asset/img/landing/img2.png
  asset/img/landing/img3.png
  asset/img/signin/Component 3.png
  asset/img/signin/Vector.png
  asset/img/signin/eye-on.png
  asset/img/signin/google.png
  asset/img/signin/logo.png
  asset/img/signup/Component 3.png
  asset/img/signup/Linkbrary.png
  asset/img/signup/Vector.png
  asset/img/signup/eye-on.png
  asset/img/signup/google.png
  css/color.css
  faq/index.html
  folder/index.html
  folder/style.css
  img/signin/Vector.png
  img/signup/Vector.png
  index.html
  landing/index.html
  landing/style.css
  privacy/index.html
  signin.html
  signin/index.html
  signin/index.js
  signin/style.css
  signup/index.html
  signup/index.js
  signup/style.css
  styles/color.css
  styles/common.css
Labels: 매운맛🔥

#168 [김세동] Week4
  Assets/Icons/eye-off.svg
  Assets/Icons/eye-on.svg
  Assets/Icons/footer_X.png
  Assets/Icons/footer_facebook.png
  Assets/Icons/footer_instagram.png
  Assets/Icons/footer_youtube.png
  Assets/Icons/google.svg
  Assets/Icons/social_kakaotalk.png
  Assets/images/PreviewImage.png
  Assets/images/landingPage/main_Image.png
  Assets/images/landingPage/main_image1.png
  Assets/images/landingPage/main_image2.png
  Assets/images/landingPage/main_image3.png
  Assets/images/landingPage/main_image4.png
  Assets/kakaoin.svg
  Assets/kakaoout.svg
  Assets/logos/logo.svg
  JavaScript/passwordHide.js
  JavaScript/signin.js
  Style.css
  Styles/defaultStyle.css
  Styles/landingPage.css
  Styles/reset.css
  Styles/signPage.css
  folder.html
  index.html
  signIn.html
  signup.html
  toDo.txt
Labels: 매운맛🔥

#253 [이지수] week4
  assets/index/_img.png
  assets/index/_img1.png
  assets/index/_img4.png
  assets/index/akar-icons_facebook-fill.svg
  assets/index/akar-icons_twitter-fill.svg
  assets/index/akar-icons_youtube-fill.svg
  assets/index/ant-design_instagram-filled.svg
  assets/index/img2.png
  assets/index/img3.png
  assets/index/logo.svg
  assets/signin/Component 2.svg
  assets/signin/Component 3.svg
  assets/signin/eye-off.svg
  assets/signin/logo.svg
  index.html
  signin.html
  signin.js
  signup.html
  styles/main.css
  styles/reset.css
  styles/signup.css
  styles/style.css
  styles/theme.css
Labels: 미완성, 순한맛🐑 

#248 [김민영]Week4
  4-Weekly-Mission.code-workspace
  css/main-style.css
  css/sign-style.css
  faq.html
  folder.html
  img/google-icon.svg
  img/kakao-icon.svg
  img/logo.svg
  img/sign-logo.png
  index.html
  js/sign.js
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#213 [조한빈] Week4
  assets/icons/common/google.png
  assets/icons/common/kakao.svg
  assets/icons/landing/sns/facebook.png
  assets/icons/landing/sns/instagram.png
  assets/icons/landing/sns/twitter.png
  assets/icons/landing/sns/youtube.png
  assets/images/common/logo.png
  assets/images/common/logo.svg
  assets/images/landing/main1.png
  assets/images/landing/main2-0.png
  assets/images/landing/main2-1.png
  assets/images/landing/main2-2.png
  assets/images/landing/main2-3.png
  assets/images/landing/main3.png
  assets/images/landing/main4.png
  assets/images/landing/main5.png
  assets/images/og/ogimage.jpg
  folder/index.html
  index.html
  signin/index.html
  signin/index.js
  signin/style.css
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛🔥

#201 [김혜중]Week4
  css/global.css
  css/index.css
  css/reset.css
  css/sign.css
  folder.html
  index.html
  js/sign.js
  signin.html
  signup.html
Labels: 매운맛🔥

#266 [손승현] Week 4
  css/index.css
  css/palette.css
  css/sign.css
  folder.html
  index.html
  signin.html
  signin.js
  signup.html
Labels: 매운맛🔥

#240 [이승훈] week4
  css/colors.css
  css/signIn.css
  html/faq.html
  html/folder.html
  html/privacy.html
  html/signIn.html
  html/signUp.html
  images/signIn/eye-on.png
  index.html
  js/sign.js
Labels: 매운맛🔥

#190 [김시현] Week4
  css/color.css
  css/global.css
  css/landing.css
  css/sign.css
  folder.html
  public/images/eye-off.svg
  public/images/eye-on.svg
  signin.html
  src/constants/VALIDATION.js
  src/sign.js
Labels: 매운맛🔥

#278 Part1 김태은 week4
  index.html
  signin.html
  signup.html
  src/landing.css
  src/sign.css
  src/sign.js
Labels: 매운맛🔥, 미완성

#194 [이진호] Week4
  .github/pull_request_template.md
  folder.html
  images/eye-on.svg
  js/signin.js
  signin.html
  signup.html
  src/landing.css
  src/sign.css
Labels: 매운맛🔥

#218 [여승구]Week4
  folder/test.html
  images/eye-on.svg
  index.html
  scripts/sign.js
  signin.html
  signup.html
  src/common.css
  src/sign.css
  src/style.css
Labels: 순한맛🐑 

#233 [이서인] Week4
  signin.css
  signin.html
  signin.js
Labels: 매운맛🔥

#202 [박지윤] Week4
  folder.html
  images/eye-on.svg
  sign.js
  signin.html
  style/sign.css
Labels: 매운맛🔥

#182 [이재성] Week4
  images/eye-on.svg
  index.html
  js/sign.js
  js/validate.js
  pages/faq.html
  pages/privacy.html
  pages/signin.html
  pages/signup.html
  src/landing.css
  src/sign.css
Labels: 매운맛🔥

#274 [김도현] Week4
  assets/icons/icon_google.png
  assets/icons/icon_kakao.png
  js/login.js
  signin.html
  signup.html
  style/login.css
Labels: 순한맛🐑 

#186 [김민정] Week4
  assets/icons/eye-on.png
  folder.html
  index.html
  js/login.js
  signin.html
  signup.html
  style/login.css
  style/style.css
Labels: 매운맛🔥

#220 [구승모] week4
  css/signin.css
  folder.html
  index.html
  js/signin/constants.js
  js/signin/signin.js
  signin.html
  signup.html
Labels: 매운맛🔥

#222 [안주언] week 4
  signin/index.html
  signin/index.js
  signin/logo.svg
  signin/style.css
Labels: 매운맛🔥

#208 [황준용]Week4
  folder.html
  images/eye-on.svg
  js/sign.js
  signin.html
  src/sign.css
Labels: 매운맛🔥

#254 이진우 Week4
  signin.html
  signin.js
Labels: 매운맛🔥, 미완성

#209 [홍재훈] Week4
  linkbrary/css/signin.css
  linkbrary/css/signup.css
  linkbrary/image/eye_off_icon.png
  linkbrary/image/eye_on_icon.png
  linkbrary/image/footer_facebook_icon.png
  linkbrary/image/footer_instagram_icon.png
  linkbrary/image/footer_twitter_icon.png
  linkbrary/image/footer_youtube_icon.png
  linkbrary/image/google_social_login.png
  linkbrary/image/header_logo.png
  linkbrary/image/kakako_social_login.png
  linkbrary/image/sign_page_logo.png
  linkbrary/index.html
  linkbrary/pages/folder.html
  linkbrary/pages/signin.html
  linkbrary/pages/signup.html
  linkbrary/script/signin.js
  linkbrary/script/signup.js
  새 폴더/fff.txt
Labels: 매운맛🔥

#172 [ 윤병현 ] Week4
  css/index.css
  css/sign.css
  index.html
  js/login.js
  sign.html
Labels: 매운맛🔥

#204 [김형권] Week4
  images/eye.svg
  index.js
  signin.html
  src/landing.css
  src/sign.css
  success.html
Labels: 매운맛🔥

#281 [황은애] Week4
  test.html
Labels: 미완성, 순한맛🐑 

#199 [정사비비] Week4
  faq/faq.html
  folder/folder.html
  index.html
  privacy/privacy.html
  signin.html
  signin/signin-style.css
  signin/signin.html
  signin/signin.js
  signup.html
  signup/signup-style.css
  signup/signup.html
  style.css
Labels: 매운맛🔥

#180 [김준영] Week4
  src/css/index.css
  src/css/login.css
  src/folder.html
  src/index.html
  src/js/signin.js
  src/resource/eye_close_icon.png
  src/resource/eye_open_icon.png
  src/signin.html
  src/signup.html
Labels: 매운맛🔥
