Repository codeit-bootcamp-frontend/4-Weekly-Mission, pull requests merged in 2024-04, with the labels that each got.

#953 [신민철] Week14
  README.md
  components/AddFolderModal.tsx
  components/AddLinkModal.tsx
  components/Card.tsx
  components/DeleteFolderModal.tsx
  components/DeleteLinkModal.tsx
  components/EditModal.tsx
  components/Footer.tsx
  components/Header.tsx
  components/Input.tsx
  components/InputContainer.tsx
  components/ModalData.tsx
  components/Regex.ts
  components/ShareModal.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/api/api.ts
  pages/folder.tsx
  pages/index.tsx
  pages/shared.tsx
  pages/signin.tsx
  public/avatar.svg
  public/check.svg
  public/close.svg
  public/facebook.svg
  public/favicon.ico
  public/google.svg
  public/instagram.svg
  public/kakao logo.svg
  public/kakao.svg
  public/kebab.svg
  public/link.svg
  public/logo.svg
  public/next.svg
  public/passwordOff.svg
  public/passwordOn.svg
  public/profileImg.svg
  public/search.svg
  public/star.svg
  public/twitter.svg
  public/undefinedImg.svg
  public/vercel.svg
  public/youtube.svg
  styles/AddFolderModal.module.css
  styles/AddLinkModal.module.css
  styles/Card.module.css
  styles/DeleteFolderModal.module.css
  styles/DeleteLinkModal.module.css
  styles/EditModal.module.css
  styles/Folder.module.css
  styles/Footer.module.css
  styles/Header.module.css
  styles/Home.module.css
  styles/Input.module.css
  styles/InputContainer.module.css
  styles/ShareModal.module.css
  styles/Shared.module.css
  styles/Signin.module.css
  styles/globals.css
  yarn.lock
Labels: 매운맛🔥

#1006 [김시현] week15
  package-lock.json
  package.json
  public/icon/google-icon.svg
  public/icon/kakaotalk-icon.svg
  public/icon/linkbraryLogo.svg
  src/api/authAPI.ts
  src/api/instance.ts
  src/components/common/button/Button.tsx
  src/components/common/button/TabButton.tsx
  src/components/common/form/Form.tsx
  src/components/common/gnb/UserBtn.tsx
  src/components/folder/FixedLinkBar.tsx
  src/components/folder/FolderGridCard.tsx
  src/components/folder/FolderHeader.tsx
  src/components/folder/modal/InputFormModal.tsx
  src/components/sign/SignTitle.tsx
  src/components/sign/SocialMediaSign.tsx
  src/components/template/SignLayout.tsx
  src/constants/API.ts
  src/constants/FORM_DEFAULT.ts
  src/constants/FORM_INFO.ts
  src/constants/FORM_MESSAGE.ts
  src/hooks/api/auth/useSignInMutation.ts
  src/hooks/api/auth/useSignUpMutation.ts
  src/hooks/useAuthRedirect.ts
  src/interfaces/componentsInterface.ts
  src/pages/_app.tsx
  src/pages/folder.tsx
  src/pages/index.tsx
  src/pages/shared.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
Labels: 매운맛🔥

#983 [조한빈] Week15
  component/FolderList/index.tsx
  component/FolderList/style.js
  component/FolderOption/index.tsx
  component/FolderOwner/index.tsx
  component/Input/Input.module.css
  component/Input/index.tsx
  component/LinkAddInput/style.js
  component/LinkItems/LinkItem/index.tsx
  component/LinkItems/index.tsx
  component/LinkSearchInput/style.js
  component/LoginBtn/LoginBtn.module.css
  component/LoginBtn/index.tsx
  component/SocialLogin/SocialLogin.module.css
  component/SocialLogin/index.tsx
  lib/axios.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/folder.tsx
  pages/index.tsx
  pages/shared.tsx
  pages/signin.tsx
  pages/signup.tsx
  public/images/eye-off.svg
  public/images/eye-on.svg
  public/images/googleLogin.png
  public/images/kakaoLogin.svg
  styles/Folder.js
  styles/Signin.module.css
  styles/Signup.module.css
  styles/colors.css
  styles/globals.css
  utils/checkEmailValidity.ts
  utils/checkNewEmail.ts
  utils/checkNewPassword.ts
  utils/checkPasswordValidity.ts
  utils/confirmPassword.ts
Labels: 매운맛🔥, 미완성

#1000 [김재영]Week15
  pages/folder.tsx
  pages/shared.tsx
  public/svgs/facebookLogo.svg
  public/svgs/instagramLogo.svg
  public/svgs/mainLogo.svg
  public/svgs/twitterLogo.svg
  public/svgs/youtubeLogo.svg
  src/components/Card.tsx
  src/components/CardList.tsx
  src/components/FolderList.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Information.tsx
  src/components/LinkAddBar.tsx
  src/components/LinkSearchBar.tsx
  src/components/PopOver.tsx
  src/components/Profile.tsx
  src/components/Sign/SignForm.tsx
  src/components/modals/AddModal.tsx
  src/components/modals/ModalElements.tsx
  src/constants/fetchConstants.ts
  src/constants/signConstants.ts
  src/constants/urls.ts
  src/hooks/useCardsData.ts
  src/hooks/useFoldersData.ts
  src/hooks/useInformationData.ts
  src/hooks/useLinksData.ts
  src/types/interfaces/fetchDatas.ts
Labels: 매운맛🔥

#980 [김세동] week15
  package-lock.json
  package.json
  pages/_app.tsx
  pages/folder.tsx
  pages/index.tsx
  pages/input.tsx
  pages/share.tsx
  pages/signin.tsx
  pages/signup.tsx
  postcss.config.js
  public/favicon.ico
  public/favicon.png
  src/components/layout/footer/Footer.style.tsx
  src/components/layout/footer/Footer.tsx
  src/components/layout/head-nav/HeadNav.style.tsx
  src/components/layout/head-nav/HeadNav.tsx
  src/components/layout/head-nav/profile/Profile.style.tsx
  src/components/layout/head-nav/profile/Profile.tsx
  src/components/layout/primary-button/PrimaryButton.tsx
  src/components/layout/sign-page/header/SignPageHeader.style.tsx
  src/components/layout/sign-page/header/SignPageHeader.tsx
  src/components/layout/sign-page/social/SocialSign.style.tsx
  src/components/layout/sign-page/social/SocialSign.tsx
  src/components/sign-input/SignInput.style.tsx
  src/components/sign-input/SignInput.tsx
  src/constant/SIGN_INPUT_TEXTS.ts
  src/constant/SIGN_INPUT_TYPE_TRANSLATOR.ts
  src/constant/TEMPORARY_USER_CONSTANT.tsx
  src/containers/folder-page/folder-link-add-form/FolderLinkAddForm.style.tsx
  src/containers/folder-page/useFolderPage.tsx
  src/containers/share-page/useSharePage.tsx
  src/containers/signin-page/useSignInPage.tsx
  src/containers/signup-pagea/useSignUpPage.tsx
  src/utils/sign-blur-error-message/input-blur-types/emailBlur.ts
  src/utils/sign-blur-error-message/input-blur-types/passCheckBlur.ts
  src/utils/sign-blur-error-message/input-blur-types/passwordBlur.ts
  src/utils/sign-blur-error-message/signBlurError.ts
  styles/globals.css
  styles/pages/sign-page.style.tsx
  tailwind.config.js
Labels: 매운맛🔥

#979 [김수환] week15
  app/layout.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  components/SigninForm.tsx
  components/SignupForm.tsx
Labels: 매운맛🔥

#1011 [양서연] Week15
  components/AddLinkIcon.tsx
  components/CloseIconImage.tsx
  components/FolderList.tsx
  components/LinkCard.tsx
  components/LinkList.tsx
  components/Navbar.tsx
  components/SignInput.tsx
  constants/signInput_constant.ts
  modal/addLinkModal/AddLinkModal.tsx
  modal/shareModal/ShareModal.tsx
  pages/folder.tsx
  pages/index.tsx
  pages/signin.tsx
  pages/signup.tsx
  public/images/Icon_Google.svg
  public/images/Icon_Kakao2.svg
  styles/Home.module.css
  styles/SignInput.module.css
  styles/SignPage.module.css
  types/type.ts
  utils/api.ts
  utils/checkValid.ts
Labels: 매운맛🔥, 미완성

#1031 [김보경] week15
  app/page.tsx
  app/signin/page.tsx
  next.config.mjs
  package-lock.json
  package.json
  src/asset/index.ts
  src/asset/svg/EyeIcon.tsx
  src/asset/svg/EyeOffIcon.tsx
  src/asset/svg/EyeOnIcon.tsx
  src/asset/svg/LinkImageEmptyCaseIcon.tsx
  src/asset/svg/LinkbraryIcon.tsx
  src/components/Auth/Auth.tsx
  src/components/Auth/AuthHookForm.module.scss
  src/components/Auth/AuthHookForm.tsx
  src/components/Auth/InputField/Input/Input.module.scss
  src/components/Auth/InputField/Input/Input.tsx
  src/components/Auth/InputField/InputField.module.scss
  src/components/Auth/InputField/InputField.tsx
  src/components/Auth/SignInForm/SignInForm.module.scss
  src/components/Auth/SignInForm/SignInForm.tsx
  src/components/AuthForm/AuthLabel/AuthLabel.tsx
  src/components/Header/Header/Header.tsx
  src/components/Input/Input.tsx
  src/components/LinkManager/LinkList/LinkOverview/LinkOverView.tsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalBasic/ModalBasic.module.scss
  src/components/Modal/ModalBasic/ModalBasic.tsx
  src/components/Modal/ModalBasic/ModalHeader.tsx
  src/components/Modal/ModalBasic/ModalMain.tsx
  src/components/Modal/ModalBasic/ModalShareBtns.tsx
  src/constants/regex.ts
  src/utils/getValidUrl.ts
Labels: 매운맛🔥, 미완성

#991 [기송은] week15
  api/index.tsx
  components/Input.module.css
  components/Input.tsx
  components/Navbar.tsx
  components/folder/AddLink.tsx
  components/folder/FolderLinkList.tsx
  components/shared/CardList.tsx
  components/shared/Favorites.tsx
  package-lock.json
  package.json
  pages/index.tsx
  pages/signin.module.css
  pages/signin.tsx
  pages/signup.module.css
  pages/signup.tsx
  public/images/signin-image/google-icon.png
  public/images/signin-image/google.png
  public/images/signin-image/kakao.png
  public/images/signin-image/yellow.png
  styles/globals.css
Labels: 매운맛🔥

#1017 [정봉찬] Week15
  next.config.js
  pages/_app.page.tsx
  pages/_app.tsx
  pages/_document.page.tsx
  pages/folder/index.page.tsx
  pages/index.page.tsx
  pages/shared/index.page.tsx
  pages/shared/styles/shared.module.css
  public/images/google_login.png
  public/images/kakaotalk_login.png
  public/svgs/logo_linkbrary.svg
  src/apis/api.ts
  src/components/CardList/Card.tsx
  src/components/CardList/CardList.tsx
  src/components/Layout/Header/Header.tsx
  src/components/Layout/MainLayout/MainLayout.module.css
  src/components/Layout/MainLayout/MainLayout.tsx
  src/components/Layout/SignLayout/SignLayout.module.css
  src/components/Layout/SignLayout/SignLayout.tsx
  src/components/Layout/index.ts
  src/components/SearchBox/SearchBox.tsx
  src/components/SearchBox/SearchBoxLink.tsx
  src/components/TabList/Tab.tsx
  src/components/TabList/TabList.tsx
  src/constants/validation.ts
  src/contexts/LoginContext.tsx
  src/types/card.type.ts
  src/types/folder.type.ts
  src/types/props.type.ts
  src/types/user.type.ts
  styles/@common/colors.css
  styles/@common/fonts.css
  styles/@common/global.css
  styles/@common/reset.css
  styles/globals.css
  styles/pages/Folder.styled.tsx
  styles/pages/Home.module.css
Labels: 매운맛🔥, 미완성

#974 [김준영] Week15
  .idea/workspace.xml
  components/auth/SocialLogin.tsx
  components/folder/card/Card.tsx
  components/folder/card/CardList.tsx
  components/folder/input/SearchInputForm.tsx
  components/folder/layout/FolderHeaderLayout.tsx
  components/folder/layout/MainLayout.tsx
  components/folder/tag/Tag.tsx
  components/folder/tag/TagList.tsx
  components/sharing/Button.tsx
  components/sharing/Header.tsx
  components/sharing/Icons.tsx
  components/sharing/Kebab.tsx
  components/sharing/Popover.tsx
  components/sharing/input/LoginInputForm.tsx
  components/sharing/modal/Modal.tsx
  components/sharing/modal/ModalButton.tsx
  components/sharing/modal/ModalFolderItem.tsx
  components/sharing/modal/ModalFolderList.tsx
  components/sharing/user/Avatar.tsx
  components/sharing/user/UserProfile.tsx
  contexts/FolderContext.tsx
  next.config.js
  package-lock.json
  package.json
  pages/folder.tsx
  pages/index.tsx
  pages/inputtest.tsx
  pages/linkdetail.tsx
  pages/signin.tsx
  pages/signup.tsx
  public/icons/google.svg
  public/icons/kakao_login.svg
  styles/auth.ts
  utils/api.ts
  utils/axios.ts
  utils/constants.ts
  utils/dateUtils.ts
  utils/types.ts
Labels: 매운맛🔥

#1027 [윤아영] week15
  api/api.ts
  components/common/FolderList.tsx
  components/common/LinkCard.tsx
  components/common/LinkInfo.tsx
  components/common/Popover.tsx
  components/common/modal/Add.tsx
  components/common/modal/AddFolder.tsx
  components/common/modal/DeleteFolder.tsx
  components/common/modal/DeleteLink.tsx
  components/common/modal/Edit.tsx
  components/common/modal/Share.tsx
  components/common/modal/frame/Frame.tsx
  components/layout/Layout.tsx
  components/layout/footer/IconWithLink.tsx
  components/layout/header/Header.tsx
  components/pages/folder/LinkList.tsx
  components/pages/sign/InputGroup.tsx
  constants/footerItems.ts
  constants/sign.ts
  context/createContext..tsx
  context/sampleFolderContext.tsx
  package-lock.json
  package.json
  pages/folder/[id].tsx
  pages/folder/index.tsx
  pages/shared.tsx
  pages/signin.tsx
  pages/signup.tsx
  styles/sign.module.css
Labels: 미완성, 순한맛🐑 

#1043 [김태진] week16
  api/api.ts
  api/auth.ts
  api/axios.ts
  api/share.ts
  api/user.ts
  components/AddLinkModal/index.tsx
  components/AddModal/index.tsx
  components/CardList/index.tsx
  components/DeleteModal/index.tsx
  components/FolderAddLinkArea/index.tsx
  components/FolderAddLinkArea/styles.module.css
  components/FolderCard/index.tsx
  components/FolderCategory/index.tsx
  components/FolderControl/index.tsx
  components/FolderHeader/index.tsx
  components/FolderMain/index.tsx
  components/Header/index.tsx
  components/Input/index.tsx
  components/Input/styles.module.css
  components/Modal/ModalType.ts
  components/Modal/index.tsx
  components/ModifyModal/index.tsx
  components/PopOver/index.tsx
  components/ShareModal/index.tsx
  context/modalContext.tsx
  middleware.ts
  package-lock.json
  package.json
  pages/folder/[[...id]]/index.tsx
  pages/folder/[[...id]]/styles.module.css
  pages/folder/index.tsx
  pages/share/[folderId]/index.tsx
  pages/share/[folderId]/styles.module.css
  pages/share/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  types/index.ts
  utils/cookie.ts
Labels: 매운맛🔥

#1036 [황경수] week15
  next.config.js
  pages/_app.tsx
  pages/api/hello.ts
  pages/folder.tsx
  pages/index.tsx
  pages/login.style.ts
  pages/login.tsx
  pages/signin.style.ts
  pages/signin.tsx
  pages/signup.style.ts
  pages/signup.tsx
  src/Main.tsx
  src/api.tsx
  src/assets/image/sign-google.png
  src/assets/image/sign-kakao.png
  src/components/Modal/FolderAddList.tsx
  src/components/Modal/ModalBase.tsx
  src/components/Modal/ShareSnsList.tsx
  src/components/common/Header.tsx
  src/components/folder/AddLink.tsx
  src/components/folder/Dropdown.tsx
  src/components/folder/FoderOptionMenu.tsx
  src/components/folder/FolderButton.tsx
  src/components/folder/FolderInfo.tsx
  src/components/shared/Card.tsx
  src/components/sign/ErrorMessages.js
  src/components/sign/Input.jsx
  src/components/sign/Input.style.ts
  src/components/sign/SignHeader.jsx
  src/components/sign/SignHeader.style.ts
  src/components/sign/SignSns.jsx
  src/components/sign/SignSns.style.ts
  src/components/sign/SigninForm.style.ts
  src/components/sign/SigninForm.tsx
  src/components/sign/SignupForm.tsx
  src/index.css
  tsconfig.json
Labels: 매운맛🔥

#1040 [양서연] Week16
  components/AddLinkIcon.tsx
  components/FolderList.tsx
  components/FolderMenu.tsx
  components/Footer.tsx
  components/Header.tsx
  components/LinkAdd.tsx
  components/LinkCard.tsx
  components/Navbar.tsx
  components/SearchBar.tsx
  components/SearchIconImage.tsx
  components/SignInput.tsx
  constants/folderlist_mock_data.ts
  constants/signInput_constant.ts
  modal/addLinkModal/AddLinkModal.tsx
  modal/shareModal/ShareModal.tsx
  next.config.js
  pages/folder/[folderId].tsx
  pages/folder/index.tsx
  pages/index.tsx
  pages/shared/[folderId].tsx
  pages/signin.tsx
  pages/signup.tsx
  public/images/Icon_Google.svg
  public/images/Icon_Kakao2.svg
  public/images/logo.svg
  styles/FolderList.module.css
  styles/FolderMenu.module.css
  styles/Footer.module.css
  styles/Header.module.css
  styles/SignPage.module.css
  tsconfig.json
  types/type.ts
  utils/api.ts
Labels: 매운맛🔥
